// pattern-pools — rewrite/normalize varyant havuzları (W4 TEK KAYNAK).
// rewrite-short-items.mjs ve normalize-patterns.mjs buradan import eder.
// Her varyant: ${T} (başlık) gömülü, ölçü/eşik/mekanizma taşır, FORBIDDEN
// imzalarıyla çakışmaz. Sayılar hash-varyasyonludur ama maskeli-imza cümle
// YAPISINA bağlıdır — çeşitlilik = yapı çeşitliliği (W4 normalizasyon matematiği:
// grup ≤9 için varyant sayısı ≥ şablonlu-madde/9).

export function hashStr(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h;
}
const pk = (arr, h, salt) => arr[(h + salt) % arr.length];

export function poolsFor(n) {
  const T = n.title;
  const h = hashStr(n.id);
  const P95 = pk([250, 300, 400, 500], h, 1);
  const RL = pk([60, 120, 300], h, 2);
  const SR = pk([30, 60, 90], h, 3);
  const RB = pk([5, 10, 15], h, 4);
  const CX = pk([8, 10, 12], h, 5);
  const HIT = pk([90, 95, 98], h, 6);
  const SW = pk([30, 60, 120], h, 7);
  const LAG = pk([5, 15, 30], h, 8);
  const KB = pk([150, 200, 250], h, 9);
  const CS = pk([300, 500, 800], h, 10);
  const LK = pk([50, 100, 200], h, 11);
  const TO = pk([3, 5, 10], h, 12);
  const BM = pk([10, 20, 30], h, 13);

  return {
    performance: [
      `${T} kritik yolunda p95 ${P95}ms eşiğine bağlanır; RED duration metriğiyle izlenir`,
      `yük regresyon testi CI eşiğiyle korunur; keyset sayfalama/indeks planı ${T} sorguları için gözden geçirilir`,
      `ölçüm noktası: ${T} uç gecikmesi; eşik aşımı alarmı error-budget'a bağlıdır`,
      `darboğaz analizi ${T} için profiling ile yapılır; bütçe aşımı build uyarısı üretir`,
      `${T} sorgu planı EXPLAIN ile gözden geçirilir; regresyon eşiği p99 ${P95 + 100}ms`,
      `önbellek isabet hedefi ${T} okumaları için %${HIT}; stale pencere ${SW} sn ile sınırlıdır`,
      `önbellek kaçırma oranı ${T} sıcak anahtarlarında izlenir; ısıtma stratejisi tanımlıdır`,
      `kuyruk gecikmesi ${T} tüketicisinde ${LAG} sn eşiğiyle izlenir; aşımda backpressure devreye girer`,
      `üretici/tüketici dengesi ${T} akışında lag metriğiyle korunur; birikim alarmı kuruludur`,
      `paket boyutu bütçesi ${T} görünümü için ${KB} KB; hydration süresi ölçülür ve raporlanır`,
      `ilk-boya/hydration bütçesi ${T} ekranında sürümlenir; aşım build'de görünür`,
      `soğuk başlangıç bütçesi ${T} için ${CS} ms; init profili sürüm karşılaştırmalıdır`,
      `çalışma-zamanı bellek tavanı ${T} sürecinde izlenir; sızıntı eğilimi haftalık raporlanır`,
      `DB kilit bekleme eşiği ${T} yazma yolunda ${LK} ms; çekişme metriği panoda izlenir`,
      `uzun işlem ${T} için satır-kilidi kapsamı daraltılır; deadlock sayacı alarmlıdır`,
      `dış API zaman aşımı ${T} çağrılarında ${TO} sn; yeniden-deneme bütçesi toplam gecikmeyi sınırlar`,
      `dış bağımlılık yavaşlaması ${T} akışını bloklamaz; eşzamanlılık sınırı ve kuyruk tamponu tanımlıdır`,
      `toplu iş süresi ${T} için ${BM} dk SLO'suna bağlıdır; sapma trend raporuna düşer`,
      `gece toplu koşusu ${T} penceresi dışına taşarsa bölümleme (chunking) devreye girer`,
      `eşzamanlı istek tavanı ${T} için yük profiliyle belirlenir; aşımda kuyruk derinliği alarmı`,
      `sayfalama penceresi ${T} listelerinde sabit maliyetlidir; ofset büyümesi imleçle engellenir`,
      `sıcak yol ${T} için ayrılmış ölçümle korunur; p50/p95 makası daralması hedeflenir`,
      `kaynak bütçesi ${T} işleri için CPU/IO kotalıdır; komşu iş etkisi izole edilir`,
      `ısınma sonrası kararlılık ${T} için ölçülür; jitter eşiği tanımlıdır`,
      `${T} istek birleştirme (batching/debounce) stratejisi tanımlıdır`,
      `ön-hesaplama/projeksiyon ${T} okuma yolunu sabit maliyete indirir`,
      `${T} büyük yük (payload) sıkıştırma ve alan-seçimi ile sınırlandırılır`,
      `arka plan yenileme ${T} önbelleğini kullanıcıyı bekletmeden tazeler`,
      `${T} yavaş-sorgu günlüğü eşiklidir; plan regresyonu haftalık incelenir`,
      `kademeli yükleme ${T} listelerinde iskelet-durumla desteklenir`,
      `${T} p95 hedefi sürüm notunda beyanlıdır; regresyon kabul edilmez`,
      `ölçek testi ${T} için hedef-yükün 2 katında koşulur; kırılma noktası bilinir`,
      `${T} istemci-taraf ölçümü (web-vitals) gerçek kullanıcı verisiyle izlenir`,
      `${T} sıcak sorgu seti indeks kapsamındadır; p95 ${P95}ms aşan sorgu plan incelemesine düşer`,
      `okuma yolu ${T} için imleç (cursor) sayfalamayla sabit maliyetlidir; sayfa hedefi p95 ${P95}ms`,
      `${T} toplu okumaları N+1 taramasından geçer; yük testi eşiği p95 ${P95}ms CI'dadır`,
      `materyalize projeksiyon ${T} raporlarını önbellekten sunar; tazeleme SLO'su ${SW} sn`,
      `${T} önbellek anahtar şeması sürümlüdür; isabet hedefi %${HIT}, yük regresyonu eşiklidir`,
      `derin-ofset ${T} listelerinde keyset ile engellenir; sorgu bütçesi p99 ${P95 + 100}ms`,
      `${T} indeks sağlığı (kullanılmayan/şişkin indeks) aylık raporlanır; sorgu hedefi p95 ${P95}ms`,
      `${T} eşzamanlılık tavanı yük testiyle belirlenir; hedef p95 ${P95}ms korunur`,
      `yavaş uç raporu ${T} için haftalıktır; p95 ${P95}ms üstü uçlar indeks/önbellek incelemesine girer`,
      `${T} veri hacmi büyüme projeksiyonuna göre sayfalama stratejisi seçilir; hedef sabit maliyettir`,
    ],
    integration: [
      `${T} contract testiyle korunur; sözleşme kırılırsa CI kırmızı yakar (data-api-contract)`,
      `olay veriyolu yayını ${T} için idempotent tüketici sözleşmesine bağlıdır`,
      `bağımlılık yönü ${T} için yalnız aşağı; tipli arayüz dışı çağrı testle engellenir`,
      `${T} şema değişikliği tüketicilere expand-contract adımıyla duyurulur`,
      `geriye-uyumsuz değişiklik ${T} sözleşme sürümünü artırır; uyum matrisi CI koşusundadır`,
      `${T} tüketici sürüm matrisi CI'da koşar; kırık sürüm erken uyarı üretir`,
      `zaman aşımı/yeniden deneme bütçesi ${T} çağrıları için sözleşmede beyanlıdır`,
      `${T} olay şeması sürümlüdür; bilinmeyen alan toleransı tüketici testinde doğrulanır`,
      `çift-yazım/kesin-okuma geçişi ${T} entegrasyonunda gölge-trafikle doğrulanır`,
      `${T} dış sistem hatasında telafi (compensation) adımı tanımlıdır; saga izlenir`,
      `sözleşme örnek-yükleri ${T} için fixture olarak sürümlenir; drift testte yakalanır`,
      `${T} API kapısı dışı erişim lint/testle yasaklıdır; kapı sözleşmesi tek giriştir`,
      `olay sırası garantisi ${T} için anahtar-bazlı bölümleme ile sağlanır`,
      `${T} geri-basınç sinyali tüketiciden üreticiye sözleşmeyle taşınır`,
      `kısmi hata ${T} entegrasyonunda ayrık sonuç kodlarıyla raporlanır; sessiz yutma yasaktır`,
      `${T} bağımlılık grafiği üretimde döngüsüzdür; yeni kenar mimari incelemesinden geçer`,
      `${T} idempotency anahtarı üretici tarafında sözleşmeyle belirlenir`,
      `yeniden-oynatma (replay) güvenliği ${T} tüketicisinde offset/checkpoint ile sağlanır`,
      `${T} eşzamanlı sürüm çalışması (N ve N+1) geçiş penceresinde desteklenir`,
      `ölü-uç tespiti: ${T} kullanılmayan sözleşme alanları çeyreklik temizlenir`,
      `${T} hata sözlüğü paylaşımlıdır; tüketici hata eşlemesi testlidir`,
      `sınır ötesi çağrı ${T} için korelasyon-id zorunludur; iz uçtan uca birleşir`,
      `${T} toplu (batch) uç noktası kısmi başarı sözleşmesine sahiptir`,
      `kapasite sözleşmesi: ${T} tüketici başına oran sınırı beyanlıdır`,
      `${T} sözleşme değişiklik günlüğü (changelog) tüketiciye görünürdür`,
      `kernel çekirdek sözleşmesi ${T} tarafından salt-okunur tüketilir`,
      `${T} modül sınırı anti-corruption katmanıyla korunur (contract)`,
      `sözleşme testi ${T} örnek-yük setiyle her sürümde koşar (contract)`,
      `${T} tüketici kayıt defteri (registry) sözleşme sürümüyle tutulur (contract)`,
      `modül-arası olay adlandırması ${T} için sözleşme sözlüğüne bağlıdır`,
      `${T} kernel API çağrıları zaman-aşımı sözleşmesine tabidir (contract)`,
      `${T} modül sınırında tipli API sözleşmesi vardır; kırılma contract testinde yakalanır`,
      `olay şeması ${T} sözleşmesinde sürümlüdür; tüketici uyumu veriyolu testiyle kanıtlanır`,
      `${T} kernel yeteneklerini salt-okur tüketir; bağımlılık yönü mimari testle korunur`,
      `senkron çağrı bütçesi ${T} sözleşmesinde beyanlıdır; aşım API kapısında reddedilir`,
      `${T} dış sistem eşlemesi anti-corruption katmanındadır; sözleşme örnekleri olay fixture'ıdır`,
    ],
    mobileApps: [
      `${T} PWA yüzeyinde offline taslak + dokunma alanı 44px üstü davranışıyla cihaz matrisinde doğrulanır`,
      `iOS/Android WebView + extension köprüsünde ${T} izin istemleri gerekçeli test edilir`,
      `responsive kırılımları ${T} ekranında cihaz matrisi testiyle kanıtlanır`,
      `${T} küçük-ekran akışı tek-elle kullanım hedefiyle cihazda test edilir`,
      `ağ kesintisinde ${T} kuyruklanmış işlemlerin senkronu senaryoyla doğrulanır`,
      `${T} bildirim/izin akışı platform kurallarına göre ayrı test edilir`,
      `düşük bant genişliğinde ${T} kritik akışı ölçülü gecikmeyle doğrulanır`,
      `${T} derin-bağlantı (deep link) girişleri durum kaybı olmadan açılır; senaryo testi vardır`,
      `arka plana alınan ${T} akışı durumunu korur; geri dönüş testi cihazda koşar`,
      `${T} klavye/viewport etkileşimi (güvenli alan, input kaydırma) cihazda doğrulanır`,
      `pil/veri tasarrufu modunda ${T} davranışı tanımlıdır; arka plan senkron kısıtlanır`,
      `${T} sürüm güncellemesi (OTA/store) eski önbelleği güvenli geçersiz kılar`,
      `hücresel/wifi geçişinde ${T} oturum ve yükleme davranışı testlidir`,
      `${T} erişim izni reddedildiğinde kademeli işlev kaybı senaryosu tanımlıdır`,
      `${T} kamera/dosya erişimi izin-öncesi açıklama ekranıyla test edilir`,
      `${T} çevrimdışı kuyruk çakışması son-yazan-kazanır kuralıyla çözülür; senaryo testlidir`,
      `${T} yatay/dikey yönelim değişiminde form durumu korunur`,
      `platform geri-tuşu davranışı ${T} akışında gezinme yığınıyla tutarlıdır`,
      `${T} paylaşım hedefi (share sheet) entegrasyonu cihazda doğrulanır`,
      `bildirim derin-bağlantısı ${T} ilgili ekrana durumla açılır`,
      `${T} yerel önbellek boyutu tavanlıdır; temizleme stratejisi tanımlıdır`,
      `erişilebilirlik büyütmesi mobil ${T} ekranında kırılma olmadan çalışır`,
      `${T} ilk-açılış (onboarding) akışı atlanabilir ve kaldığı yerden sürer`,
      `sertifika sabitleme/güvenli depo ${T} mobil istemcisinde etkindir`,
      `${T} mobil oturumu biyometrik/kilit entegrasyonuyla korunur (cihaz destekliyse)`,
      `cihaz saati/dilimi değişince ${T} tarih gösterimi tutarlı kalır`,
      `${T} PWA yükleme istemi uygun anda tetiklenir; reddedilirse tekrar sormaz`,
      `mobil veri kullanımı ${T} için ölçülüdür; büyük indirme wifi-tercihlidir`,
      `${T} responsive görselleri yoğunluğa göre (srcset) servis edilir`,
      `cihaz geri dönüşünde ${T} kaydırma konumu korunur`,
      `${T} mobil klavye türü alan tipine göre açılır (numeric/email)`,
      `${T} cihaz düşük-bellek sinyalinde durumunu güvenli boşaltır`,
      `mobil derin-bağlantı ${T} yetki kontrolünden geçerek açılır`,
      `${T} PWA çevrimdışı sayfası anlamlı yönlendirme içerir`,
      `cihaz dönüşünde ${T} medya oynatma durumu korunur (responsive)`,
      `${T} dokunma hedefleri arası boşluk yanlış-tıklamayı önler (44px kuralı)`,
      `mobil oturum zaman aşımı ${T} için görünür geri sayımla bildirilir`,
      `${T} iOS/Android sistem karanlık-modunu takip eder`,
      `${T} mobil formları otomatik-doldurma (autofill) ipuçlarıyla uyumludur`,
      `${T} cihaz kamera/galeri seçiminde boyut-sıkıştırma kuralı uygulanır`,
      `mobil ağ hatasında ${T} kullanıcıya yeniden-dene seçeneği sunar (pwa)`,
      `${T} responsive tablo dar ekranda kart görünümüne dönüşür`,
      `ios/android durum çubuğu ve çentik alanı ${T} yerleşiminde hesaplıdır`,
      `${T} mobil performans bütçesi etkileşime-hazır süresiyle ölçülür (cihaz)`,
      `uygulama-içi tarayıcı (webview) kısıtları ${T} akışında testlidir`,
      `${T} PWA kurulumu cihaz matrisinde doğrulanır; offline kuyruk senkronu senaryo testlidir`,
      `iOS/Android ${T} akışında dokunma hedefleri 44px üstü ölçülür; yanlış-tıklama testi koşar`,
      `${T} responsive kırılımları cihazda testlidir; offline taslak kaybolmaz (senkron kanıtı)`,
      `WebView köprüsü (bridge) ${T} yerel yeteneklerine sözleşmeli erişir; cihaz izin akışı testlidir`,
      `${T} mobil bildirimi derin-bağlantıyla açılır; offline durumda kuyruklanır ve senkronlanır`,
      `paket boyutu ${T} mobil kabuğunda bütçelidir; köprü çağrıları toplu gönderilir`,
      `${T} PWA güncellemesi arka planda iner; yeniden-yükleme istemi 44px hedefiyle sunulur`,
      `çevrimdışı-önce ${T} taslakları cihazda saklanır; senkron çatışması kural tabanlıdır (mobil)`,
    ],
    wcag: [
      `${T} ekran yolunda klavye sırası + görünür odakla; axe AAA 0 ihlal kanıtı CI'dadır`,
      `ARIA etiketleri ${T} alanlarında bire bir; kontrast 7:1 üstü doğrulanır`,
      `ekran okuyucu duyuruları ${T} akışında senaryo testiyle kanıtlanır`,
      `${T} form hataları metinle duyurulur; durum göstergesi renkten bağımsızdır`,
      `odak tuzağı taraması ${T} modal/çekmece akışında ayrıca koşulur`,
      `${T} canlı bölge (aria-live) duyuruları durum değişimlerinde doğrulanır`,
      `büyütme %200'de ${T} yerleşimi kırılmadan çalışır; taşma testi koşulur`,
      `${T} hareket/animasyon azaltma tercihi (reduced motion) desteklenir`,
      `başlık hiyerarşisi ${T} sayfasında atlamasızdır; landmark bölgeleri tanımlıdır`,
      `${T} hata özetleri odak yönetimiyle ilişkilidir; ilk hataya atlama sağlanır`,
      `karmaşık bileşen ${T} için klavye etkileşim şeması belgelidir (ok tuşları/escape)`,
      `${T} medya içerikleri alternatif metin/altyazı kuralına bağlıdır`,
      `${T} tablo/karmaşık veri başlık-hücre ilişkileriyle (scope/headers) işaretlenir`,
      `zaman sınırlı ${T} etkileşimi uzatma/duraklatma seçeneği sunar`,
      `${T} sürükle-bırak akışının klavye alternatifi vardır`,
      `otomatik oynayan içerik ${T} sayfasında durdurulabilir`,
      `${T} hata düzeltme önerisi programatik ilişkiyle sunulur (aria-describedby)`,
      `dil değişimi ${T} içeriğinde işaretlenir (lang özniteliği)`,
      `${T} özel bileşenleri isim-rol-değer üçlüsünü eksiksiz taşır`,
      `${T} bileşen odak halkası özelleştirmede de görünür kalır (erişilebilir tema)`,
      `${T} klavye kısayolları belgelidir; tek-tuş kısayolları kapatılabilir`,
      `kontrast denetimi ${T} koyu/açık temada ayrı koşulur`,
      `${T} aria-expanded/selected durumları etkileşimle senkron doğrulanır`,
      `erişilebilir ad hesaplaması ${T} bileşenlerinde test edilir (accessible name)`,
      `${T} odak sırası DOM sırasıyla tutarlıdır; görsel sıçrama testlenir`,
      `ekran okuyucu ile ${T} form doldurma uçtan uca senaryodadır`,
      `${T} hata durumunda odak ilk hatalı alana taşınır (erişilebilir akış)`,
      `${T} açılır menü ok-tuşu gezinmesi ve escape kapanışı testlidir (klavye)`,
      `ikon-only düğmeler ${T} içinde aria-label taşır`,
      `${T} durum rozetleri metin eşdeğerlidir (renk-bağımsız, kontrastlı)`,
      `sayfa başlığı ${T} görünüm değişiminde güncellenir (ekran okuyucu bağlamı)`,
      `${T} atlama bağlantısı (skip-link) ilk odakta görünür`,
      `erişilebilirlik regresyonu ${T} için PR kapısında axe ile taranır`,
      `${T} bildirim mesajları ekran okuyucuya rol=status ile duyurulur`,
      `uzun içerik ${T} sayfasında başlıklarla bölümlenir (erişilebilir tarama)`,
      `${T} tuş-tetiklemeli menüler odak kaybında güvenli kapanır (klavye)`,
      `giriş hataları ${T} alan-altı metin + aria-invalid ile işaretlenir`,
      `${T} bileşenleri klavyeyle tam gezilebilir; axe AAA taraması PR kapısında kanıtlıdır`,
      `kontrast belirteçleri ${T} temasında 7:1 üstüdür; WCAG denetim raporu sürümlüdür`,
      `${T} canlı duyuruları (aria-live) ekran okuyucu senaryosuyla ayrıca doğrulanır`,
      `odak yönetimi ${T} adım geçişlerinde korunur; etkileşim hedef boyutu 44px üstüdür`,
      `${T} form etiketleri aria ile eşlenir; hata duyurusu ekran okuyucuda testlidir`,
      `görsel-olmayan kullanım ${T} akışında klavye + ekran okuyucu birleşik senaryosuyla kanıtlanır (wcag)`,
    ],
    deployment: [
      `${T} Swarm/K8s hedefinde healthcheck probe + env-config ayrımıyla; rollback önceki imajla ${RB} dk`,
      `dağıtım kanıtı: ${T} imaj etiketi + smoke testi; geri dönüş release-versioning sözleşmesine bağlı`,
      `config/sır ayrımı ${T} ortam değişkenleriyle; drift kontrolü CI'da`,
      `${T} sürümü mavi-yeşil geçişle alınır; smoke sonrası trafik anahtarlanır`,
      `ortam farkları ${T} için tek manifest kaynağından türetilir; drift alarmı kurulur`,
      `${T} başlangıç sırası bağımlılık sağlığına bağlanır; hazır olmayan trafik almaz`,
      `kapasite: ${T} replika sayısı yük eşiğiyle otomatik ölçeklenir`,
      `${T} veritabanı migration'ı dağıtımdan ayrık adımdır; geri alınabilirlik beyanlıdır`,
      `kanarya dilimi ${T} için trafik yüzdesiyle açılır; hata eşiğinde otomatik geri çekilir`,
      `${T} imajı sabit taban + imzalı katmanlarla üretilir; üretimde paket kurulumu yasaktır`,
      `bakım penceresi gerektiren ${T} değişikliği önceden duyurulur; degrade modu tanımlıdır`,
      `${T} yapılandırma değişikliği sürümlenir; acil geri alma tek komuttur`,
      `${T} şema-uyumlu config doğrulaması başlangıçta koşar; geçersiz config açılışı durdurur`,
      `sıfır-kesinti hedefi ${T} için bağlantı boşaltma (drain) süresiyle sağlanır`,
      `${T} bölgesel yedeklilik beyanlıdır; tek-nokta hatası mimari incelemede kapatılır`,
      `dağıtım penceresi ${T} için trafik-düşük saatlere planlanır; takvim kayıtlıdır`,
      `${T} eski sürüm artefaktları saklama politikasıyla arşivlenir (hızlı geri dönüş)`,
      `ön-üretim (staging) paritesi ${T} için config-fark raporuyla doğrulanır`,
      `${T} sağlık ucu bağımlılık ayrıntısı sızdırmaz; derin-sağlık ayrı ve korumalıdır`,
      `${T} dağıtımı imza-doğrulamalı hattan çıkar; elle kopyalama yasaktır (docker)`,
      `hosting hedefi ${T} için beyanlıdır; ortama özgü koşul konfigürasyonla çözülür`,
      `${T} dağıtım sağlığı sentetik uç-kontrolle (probe) 5 dk izlenir`,
      `docker imaj boyutu ${T} için bütçelidir; katman şişmesi raporlanır`,
      `${T} hosting ortam matrisi (swarm/k8s/shared) beyanlı ve testlidir`,
      `${T} yapılandırması ortam-bazlı şablondan üretilir; elle düzenleme yasaktır (env)`,
      `${T} konteyner sağlığı bağımlılık-farkındalıklı probe ile ölçülür (docker)`,
      `sürüm etiketi ${T} artefaktına gömülüdür; çalışan sürüm uçtan sorgulanır (imaj)`,
      `${T} hosting sınırları (bellek/CPU) manifestte beyanlıdır; aşım throttle edilir`,
      `${T} dağıtımı kanarya adımıyla ilerler; sağlık probu eşik aşımında rollback tetikler`,
      `imaj üretimi ${T} için çok-aşamalı Docker build'tir; config katmanı env'den ayrık doğrulanır`,
      `${T} sürüm etiketi değişmezdir; geri dönüş ${RB} dk hedefiyle tatbikatlıdır (dağıtım)`,
      `${T} dağıtım hattı imza-doğrulamalı aşamalardan oluşur; config farkı raporlanır`,
      `${T} container kaynak istek/limitleri ölçümle ayarlanır; sağlık probu eşiklidir`,
      `${T} dağıtım geri-alma tatbikatı çeyrekliktir; rollback süresi ölçülür`,
      `ortam değişkeni şeması ${T} dağıtımında doğrulanır; eksik sır (env) açılışı durdurur`,
    ],
    securityOptimization: [
      `${T} sırları ${SR} günde rotasyonla; rate-limit ${RL} istek/dk zorlanır`,
      `bağımlılıklar pinli + SBOM taraması ${T} CI hattında; imzasız yapıt reddedilir`,
      `en az ayrıcalık gözden geçirmesi ${T} rolleri için çeyreklik kanıtlanır`,
      `${T} yüzeyinde kullanılmayan uç kapatılır; izin envanteri çeyreklik daraltılır`,
      `tedarik zinciri: ${T} bağımlılık güncellemeleri imzalı PR + kapı koşusuyla alınır`,
      `${T} hata mesajları iç detay sızdırmaz; jenerik yanıt + korelasyon id`,
      `derleme zinciri ${T} için sabitlenmiş imajla koşar; dış indirme yasak`,
      `${T} yönetici eylemleri ikinci kanal onayına bağlıdır; oturum yükseltme kayıtlıdır`,
      `çalışma-zamanı sertleştirme ${T} sürecinde en-az-yetenek (capability drop) ile uygulanır`,
      `${T} sır erişimi uygulama kimliğiyle sınırlıdır; geniş kapsamlı anahtar yasaktır`,
      `güvenlik başlıkları ${T} yanıtlarında zorunludur; eksik başlık testte yakalanır`,
      `${T} loglarında gizli değer maskesi build-time lint ile taranır`,
      `${T} oturum çerezleri Secure+HttpOnly+SameSite ile sınırlandırılır`,
      `yetki belirteci ömrü ${T} için kısadır; yenileme dönüşümlüdür (rotation)`,
      `${T} iç uçları ağ politikasıyla (deny-all) kapalıdır; açık uç envanterlidir`,
      `kripto anahtar yönetimi ${T} için KMS-tabanlıdır; anahtar dışa çıkmaz`,
      `${T} yapılandırma sırları depoda şifreli; düz metin commit taramayla engellenir`,
      `çalışma-zamanı bütünlüğü ${T} imaj özeti (digest) sabitlemesiyle korunur`,
      `${T} webhook imza doğrulaması zorunludur; imzasız istek reddedilir`,
      `kaba-kuvvet koruması ${T} girişlerinde artan-gecikme ile uygulanır`,
      `${T} sertleştirme taban çizgisi (baseline) sürümlenir; sapma raporlanır (harden)`,
      `geçici ayrıcalık ${T} için süreli verilir; otomatik geri alınır (privilege)`,
      `${T} rate-limit aşımı istemciye gecikme-başlığıyla bildirilir`,
      `${T} sırları kasada tutulur ve ${SR} günde rotasyona girer; bağımlılıklar pin'lidir`,
      `çıkış (egress) trafiği ${T} servisinde allowlist ile sınırlıdır; sır sızıntı taraması CI'dadır`,
      `${T} imaj imzası doğrulanır (signed); ayrıcalık düşürme sertleştirme listesindedir`,
      `rate-limit ${RL} istek/dk ${T} uçlarında; SBOM farkı sürüm notunda raporlanır`,
      `${T} yüzey daraltması: kullanılmayan uç kapalıdır; sır erişimi en az ayrıcalıkladır`,
      `CSP başlıkları ${T} yüzeyinde zorunludur; bağımlılık taraması eşiklidir`,
      `${T} ayrıcalık envanteri çeyreklik daralır; kullanılmayan izin kapalıdır`,
      `sertleştirme kontrol listesi ${T} imajına uygulanır; sapma taramayla yakalanır`,
      `${T} sır kapsamı servis-başına ayrıktır; çapraz erişim allowlist dışıdır`,
      `anahtar rotasyonu ${T} için otomatiktir; eski anahtar imza doğrulamasında reddedilir`,
    ],
    testing: [
      `${T} için unit + contract + negatif senaryo ayrımıyla; golden fixture kanıtı CI'da`,
      `e2e yolculuğu ${T} akışında Playwright'ta kırmızı→yeşil kanıtla bağlanır`,
      `yetkisiz erişim denemesi ${T} testinde 0 kayıt döner (negatif kanıt)`,
      `${T} sınır-değer ve hata-yolu senaryoları ayrı fixture setiyle koşulur`,
      `mutasyon testi örneklemi ${T} kritik fonksiyonlarında periyodik koşulur`,
      `${T} kabul testleri örnek yüklerle sürümlenir; kanıt PR'a bağlanır`,
      `kararlılık: ${T} testleri 3 ardışık koşuda deterministik geçer`,
      `${T} eşzamanlılık senaryosu (yarış/tekrar giriş) ayrı test sınıfındadır`,
      `test verisi ${T} için üretim-benzeri anonim setten türetilir; sabit tohumludur`,
      `${T} regresyon paketi değişen modüle göre seçimli koşar; tam paket gecelik`,
      `hata enjeksiyonu ${T} kritik bağımlılığında senaryolaştırılır (timeout/5xx)`,
      `${T} sözleşme testleri tüketici-sağlayıcı çiftinde çift yönlü koşar`,
      `${T} performans duman-testi kritik uçta eşikle koşar`,
      `sözleşme-dışı davranış ${T} testlerinde açıkça reddedilir (negatif sözleşme)`,
      `${T} unit kapsamı kritik dallarda eşiklidir; rapor PR özetindedir`,
      `${T} entegrasyon testleri golden fixture setiyle koşar; kırılma kanıtı PR'a düşer`,
      `sınır-değer üretimi ${T} unit testlerinde tablo-tabanlıdır; negatif girdiler ayrı settedir`,
    ],
    owasp: [
      `${T} yüzeyinde A01 erişim + A03 injection karşı kontrolüyle; negatif test kanıtı zorunlu`,
      `girdi doğrulama ${T} uçlarında zod sözleşmesiyle; ihlal denetim izine düşer`,
      `tehdit sınıfı eşlemesi ${T} için ASVS kontrol listesine bağlanır`,
      `${T} oturum/kimlik akışı A07 kontrol listesiyle gözden geçirilir`,
      `SSRF/dış çağrı yüzeyi ${T} için allowlist ile sınırlandırılır`,
      `${T} çıktı kodlaması bağlama göre (HTML/URL/JSON) ayrık uygulanır`,
      `yetki yükseltme denemesi ${T} akışında izlenir ve engellenir (A01 kanıtı)`,
      `${T} dosya/yükleme yüzeyi tür-boyut-içerik doğrulamasıyla korunur`,
      `kayıt/parola akışı ${T} için kaba-kuvvet limiti + kilitleme politikalıdır`,
      `${T} API numaralandırma (enumeration) koruması belirsiz-hata + oranla sağlanır`,
      `${T} kütüphane CVE taraması eşiklidir; kritik bulgu birleşmeyi bloklar`,
      `iş mantığı istismarı ${T} için kötüye-kullanım senaryolarıyla test edilir`,
      `${T} hassas işlem loglaması denetim standardına bağlıdır (A09 kanıtı)`,
      `${T} güvenlik regresyon paketi tehdit-senaryo bazlıdır; owasp eşlemesi belgelidir`,
      `${T} tehdit modeli çeyreklik gözden geçirilir; A01/A03 kontrolleri ASVS listesine bağlıdır`,
      `${T} dosya/URL girdileri SSRF filtresinden geçer; doğrulama ihlali denetim izine düşer`,
    ],
    security: [
      `${T} erişimi tenant-scoped deny-by-default kuralıyla; audit izi değişmezdir`,
      `PII alanları ${T} kapsamında maskeli; rol matrisi en az ayrıcalıkla tanımlıdır`,
      `komşu-tenant negatif testi ${T} için 0 satır döner (izolasyon kanıtı)`,
      `${T} yetki matrisi rol×eylem tablosuyla sürümlenir; sapma testi koşar`,
      `oturum yaşam döngüsü ${T} için süre + uzaktan iptal kurallarıyla tanımlıdır`,
      `${T} kritik eylemleri ikinci onay (step-up) ister; iz kaydı değişmezdir`,
      `veri erişim genişliği ${T} sorgularında satır-düzeyi filtreyle sınırlanır`,
      `${T} servis-arası çağrılar kısa ömürlü kimlikle yapılır; statik anahtar yasaktır`,
      `yetki kararları ${T} için merkezi politika noktasından (PDP) alınır; yerel bypass yasaktır`,
      `${T} denetim olayları eksiksizdir: kim-ne-nezaman-nereden alanları zorunludur`,
      `${T} veri sahipliği alan-bazlı yetkiyle ayrışır; toplu dışa aktarım onaylıdır`,
      `acil erişim (break-glass) ${T} için süreli ve tam-izlidir`,
      `${T} kimlik doğrulama başarısızlıkları oran-sınırlı ve alarmlıdır`,
      `${T} erişim kararları önbelleğe alınmaz; yetki değişimi anında etkilidir`,
      `hassas ${T} alanları kısmi-maskeyle sunulur; tam erişim ayrıca yetkilidir`,
      `${T} yetki denetimi negatif senaryolarla her sürümde koşulur (deny kanıtı)`,
      `${T} kayıt erişim izleri değişmez depoda tutulur (audit)`,
      `${T} satır-düzeyi erişim RLS ile tenant'a kilitlidir; deny kararı audit izine düşer`,
      `${T} PII dışa aktarımı maskeli ve yetki-kapılıdır; erişim denemesi denetim kaydı üretir`,
    ],
    codeOptimization: [
      `${T} karmaşıklık tavanı ${CX} lint kapısıyla zorlanır (coding-standards)`,
      `engine/görünüm ayrımı ${T} modüler sınırıyla korunur; strict tip modu açık`,
      `ölü kod elemesi ${T} refactor bütçesinde izlenir`,
      `${T} bağımlılık grafiği döngüsüz tutulur; katman ihlali lint kapısında yakalanır`,
      `ortak yardımcılar ${T} için tek pakette toplanır; kopya-blok taraması CI hattındadır`,
      `${T} genel API yüzeyi belgeli ve sürümlü; iç yardımcılar dışa kapalı`,
      `derleme süresi ${T} için bütçeli; artış CI'da raporlanır`,
      `${T} fonksiyon uzunluğu ve parametre sayısı eşiklidir; aşım incelemeye düşer`,
      `isimlendirme/dizin sözleşmesi ${T} modülünde lint ile doğrulanır`,
      `${T} hata yönetimi tek desenle (Result/istisna) yapılır; karışık kullanım yasaktır`,
      `${T} içe-aktarım sınırları paket-sınırı lint kuralıyla korunur`,
      `yan-etkisiz çekirdek ${T} için saf fonksiyon oranı izlenir`,
      `${T} genel tipler daraltılmıştır; any/unknown sızıntısı lint ile engellenir`,
      `tekrarlı mantık ${T} modülünde tek kaynaktan türetilir; kopya eşiği taramalıdır`,
      `${T} test-edilebilirlik: bağımlılıklar enjekte edilir, global durum yasaktır`,
      `ölü bayrak/feature-flag temizliği ${T} için sürüm sonrası takvimindedir`,
      `${T} kritik yolu için algoritmik karmaşıklık beyanı (Big-O) belgelidir`,
      `${T} modül sınırında tip sözleşmesi dar tutulur; iç tip dışa sızmaz`,
      `karmaşık koşullar ${T} içinde adlandırılmış yüklemlere (predicate) ayrıştırılır`,
      `${T} refactor güvenliği karakterizasyon testleriyle sağlanır`,
      `derleyici uyarıları ${T} için sıfır-tolerans; uyarı derlemeyi kırar (tip disiplini)`,
      `${T} kod-inceleme eşiği: değişiklik 400 satırı aşarsa bölünür (modüler sınır)`,
      `içe-aktarım derinliği ${T} için modüler eşiklidir; aşım lint kapısında raporlanır`,
      `${T} tip kapsamı strict'tir; any sayısı eşiklidir ve kapıda zorlanır`,
      `karmaşıklık trend raporu ${T} için haftalıktır; artış refactor bütçesine düşer (eşik)`,
      `${T} modüler paket sınırları belgelidir; çapraz içe-aktarım lint kapısında kırılır`,
      `refactor sırası ${T} için karakterizasyon testi önkoşuludur; kapsam eşiklidir`,
      `${T} tip daralması (narrowing) sınır katmanında yapılır; iç katman güvenli tiplidir`,
      `ölü kod taraması ${T} modülünde sürüm öncesi eşikli koşar; bulgu refactor bütçesine düşer`,
    ],
    featureDefs: [
      `${T} sınırı girdi/çıktı beyanı + hata yolu senaryosuyla kabul kriterine bağlanır`,
      `durum akışı ${T} için ayrık senaryo olarak sözleşme testinde doğrulanır`,
      `non-goal beyanı ${T} kapsam sınırını komşu modüle karşı korur`,
      `${T} kabul senaryoları verilen/eğer/o-zaman formatında sürümlenir`,
      `${T} çıktı sözleşmesi örnek yüklerle (sample payload) belgelenir`,
      `${T} kenar durumları (boş/maks/çakışan girdi) kabul listesinde ayrık maddedir`,
      `${T} geriye-uyum beyanı: mevcut tüketici davranışı kırılmaz`,
      `başarı ölçütü ${T} için ölçülebilir tek cümledir; belirsiz fiil kabul edilmez`,
      `${T} rol-bazlı görünürlük matrisi kabul kriterlerine eklidir`,
      `${T} veri ömrü ve boşluk-durumu (empty-state) davranışı tanımlıdır`,
      `çoklu-dil etkisi ${T} metin alanlarında beyanlıdır`,
      `${T} eşzamanlı düzenleme çakışma kuralı senaryolaştırılmıştır`,
      `${T} dışa-aktarım/rapor etkisi kapsam beyanında yer alır`,
      `${T} işlev kapsamı sürüm-notlarında kullanıcı-görünür dille özetlenir`,
      `${T} girdi sınırları (uzunluk/aralık/format) beyanlıdır; sınır aşımı hata yoludur`,
      `${T} kapsam beyanı sürümlüdür; girdi/çıktı örnek yükleri kabul testine bağlıdır`,
      `${T} işlev sınırı durum makinesiyle çizilir; geçersiz geçiş hata yolu senaryosudur`,
      `dilim tanımı ${T} için tek sorumluluk taşır; kapsam dışı istek sözleşmeyle reddedilir`,
      `${T} kabul ölçütleri çıktı-beyanlıdır; belirsiz kapsam ifadesi kapıda uyarı üretir`,
      `${T} kapsam matrisi rol×işlev tablosuyla sürümlenir; kabul testine bağlanır`,
      `komşu modülle sınır anlaşması ${T} için yazılıdır; ihlal sözleşme testinde yakalanır`,
      `${T} işlev beyanı örnek girdi/çıktı çiftleriyle somutlanır; kabul ölçütü eklidir`,
      `${T} kapsam değişikliği sürüm kaydına işlenir; durum akışı etkisi beyanlıdır`,
      `hata yolu envanteri ${T} işlev sınırında ayrık senaryolarla tutulur`,
    ],
    eca: [
      `${T} kuralları zincir derinliği 6 sınırı + idempotency anahtarıyla çalışır`,
      `dış-etkili eylem ${T} akışında insan onayı (step-up) ister; deny izi düşer`,
      `${T} kural değerlendirmesi deterministiktir; yan-etki yalnız eylem katmanındadır`,
      `koşul ifadeleri ${T} için tip-güvenli şemayla doğrulanır; serbest kod yasaktır`,
      `${T} tetik fırtınası koruması pencere-bazlı birleştirme ile sağlanır`,
      `kural değişikliği ${T} üzerinde simülasyonla önizlenir; kanıt kayda düşer`,
    ],
    aiAgents: [
      `${T} için AI yalnız öneri/taslak üretir; app-module mutasyonu deny + kill-switch`,
      `sub_prompt ${T} bağlamında güvenilmez girdi sayılır; redaksiyon zorunlu`,
      `${T} AI çıktısı şema doğrulamasından geçmeden uygulanamaz`,
      `maliyet/istek bütçesi ${T} ajan çağrılarında tavanlıdır; aşım kesilir`,
      `${T} ajan eylem günlüğü insan-okur formatta tutulur; geri izleme tamdır`,
      `araç yetki kapsamı ${T} ajanında görev-bazlı daraltılır (capability-scoped)`,
    ],
    moduleUsage: [
      `${T} tüketimi capability-scoped API/olayla; doğrudan tablo erişimi testle yasaklıdır`,
      `tüketici sözleşme testi ${T} Contract kapısı dışı çağrıyı kırmızı yakar`,
      `${T} tüketim örnekleri sürümlü tarif (recipe) olarak belgelenir`,
      `yeni tüketici ${T} için kayıt/keşif sözleşmesine uyar; gizli bağımlılık yasaktır`,
      `${T} kullanım kotası tüketici başına tanımlıdır; aşım kademeli kısıtlanır`,
      `sürüm-sonu (deprecation) ${T} tüketicilerine takvimli duyurulur`,
      `${T} yüzey değişiklikleri etki-analiz listesindeki tüketicilere işaretlenir`,
      `çapraz-modül veri ihtiyacı ${T} üzerinden projeksiyonla karşılanır; kopya tablo yasaktır`,
    ],
  };
}
