#!/usr/bin/env node
/** seed-build — Faz B19. build kümesi (22 düğüm: inşa sırası/dağıtım/anti-pattern + 4 x-kırılım). */
import { D, apply, xdim } from "./seed-docs-lib.mjs";

const CONTENT = {
  "app-build": D(
    "Build & Dağıtım",
    "Build & Dağıtım — kernel'den enterprise'a inşa sırası, referans uygulama, risk defteri ve deploy otomasyonu kümesi",
    {
      kap: "inşa fazlarını (0-7), referans uygulamayı ve dağıtım otomasyonunu toplar",
      integ: "kararlar (ADR) ve edu (faz haritası) kümeleriyle hizalı",
      ai: "AI faz hazırlık/risk özeti önerir; faz geçiş kararını ekip verir",
      mu: "Build app'i inşa ve dağıtım yol haritasını barındırır",
    },
  ),
  "app-build-x-atom": xdim("İnşa Atomu", "bölünemez bir inşa adımının örnek kırılımı"),
  "app-build-x-element": xdim("İnşa Elementi", "tek bir inşa kuralının örnek kırılımı"),
  "app-build-x-molecule": xdim("İnşa Molekülü", "birkaç inşa adımını birleştiren örnek kırılım"),
  "app-build-x-stone": xdim("İnşa Taşı", "bir inşa yeteneğinin orta-granül örnek kırılımı"),

  "build-sequence": D(
    "Build Sırası",
    "Build Sırası — Faz 0-7: Kernel → Scale primitives → Layer 1 → Layer 2 + DX → Scale proof",
    {
      kap: "inşa fazlarının zorunlu sırasını ve her fazın önkoşulunu tanımlar",
      code: "faz bağımlılığı yukarı-doğru; atlama yok (kernel önce)",
      test: "her faz çıkışında ilgili kapılar (test/tip/a11y) yeşil olmalı",
      dep: "son faz (scale proof) dağıtım kanıtı üretir",
      integ: "edu-faz-haritasi ile birebir eşlenir",
      ai: "AI faz önkoşul eksiği önerir; faz başlatma kararını ekip verir",
      mu: "Build sırası inşanın omurga takvimidir",
    },
  ),
  "build-ilk-dikey-dilim": D(
    "İlk Dikey Dilim",
    "İlk Dikey Dilim — Money'den OrderOps'a: spec'ten çalışan sisteme köprü; küçük runtime iskeleti, atomik tipler, ArcheType okuyucu",
    {
      kap: "ilk uçtan-uca çalışan dilimi (Money tipi → OrderOps) tanımlar",
      code: "küçük runtime + atomik tip + ArcheType okuyucu ile minimum çalışan sistem",
      test: "ilk dikey dilim uçtan uca testle kanıtlanır",
      dep: "dilim yerelde ve CI'da çalışır halde gösterilir",
      integ: "atomic (Money) ve referans uygulama (OrderOps) ile bağlı",
      ai: "AI dilim scaffold/test taslağı önerir; kapsam kararını ekip verir",
      mu: "İlk dikey dilim 'çalışan iskelet' kanıtını sağlar",
    },
  ),
  "build-referans-uygulama": D(
    "Referans Uygulama",
    "Kanonik Referans Uygulama — OrderOps: tanımdan deploy'a enterprise foundation kanıtı (tenancy, yetki, sipariş)",
    {
      kap: "OrderOps üzerinden tüm enterprise temelini (tenancy/yetki/audit) kanıtlar",
      sec: "tenancy izolasyonu ve yetki referans uygulamada uçtan uca gösterilir",
      code: "referans uygulama platform sözleşmelerini örnekleyen kanonik kod",
      test: "OrderOps uçtan uca + güvenlik senaryolarıyla doğrulanır",
      dep: "tanımdan deploy'a tam hat referans uygulamada işletilir",
      integ: "core-operations (sipariş) ve layer0 (tenancy) ile bağlı",
      ai: "AI referans senaryo/iyileştirme önerir; kanonik kapsam kararını ekip verir",
      mu: "Referans uygulama platform yeteneklerinin canlı kanıtıdır",
    },
  ),
  "build-enterprise": D(
    "Faz 6 Enterprise",
    "Faz 6 — Enterprise Multi-Product Operasyonu: tek panel çok app, tenant başına app aktivasyonu, Edition-tabanlı entitlement",
    {
      kap: "çok-ürün operasyonu, tenant başına app aktivasyonu ve Edition entitlement'ı tanımlar",
      sec: "entitlement yetkiyle zorlanır; tenant yalnız aktif app'lerine erişir",
      code: "Edition→app/modül eşlemesi bildirimsel (entitlement)",
      perf: "çok-app paneli lazy yüklenir; tenant kapsamı indeksli",
      eca: "app aktivasyonu olayında entitlement ve erişim güncellenir",
      integ: "aday (edition/stack) ve platform-horizontal (iam) ile hizalı",
      ai: "AI entitlement tutarsızlığı önerir; aktivasyon kararını yönetici verir",
      mu: "Faz 6 çok-ürün enterprise işletimini tanımlar",
    },
  ),
  "build-enterprise-readiness": D(
    "Enterprise Readiness",
    "Enterprise Readiness Matrisi — Release Kanıt Kapıları: güvenlikten maliyete sekiz boyutta ölçülebilir üretim çıkış kriterleri",
    {
      kap: "üretime çıkış için sekiz boyutta ölçülebilir kanıt kapısı tanımlar",
      sec: "güvenlik boyutu (pen-test/RLS/audit) çıkış kapısının parçası",
      code: "her boyut için ölçülebilir eşik bildirimsel",
      test: "tüm readiness kapıları yeşil değilse üretime çıkılmaz",
      dep: "release ancak readiness matrisi karşılanınca onaylanır",
      integ: "risk defteri ve uzman denetimiyle birlikte okunur",
      ai: "AI eksik readiness boyutu önerir; çıkış kararını insan/komite verir",
      owasp: "tüm OWASP kapıları readiness matrisinin güvenlik boyutunda",
      mu: "Enterprise Readiness üretime çıkışın ölçülebilir kapısıdır",
    },
  ),
  "build-acik-kaynak": D(
    "Faz 7 Açık Kaynak",
    "Faz 7 — Açık Kaynak Yayını: Drupal/Odoo modeli kamuya açılış; lisans temeli, CLA, topluluk altyapısı, modül pazaryeri",
    {
      kap: "kamuya açık yayın için lisans, CLA ve topluluk altyapısını tanımlar",
      sec: "açık kaynak öncesi sır taraması + güvenlik incelemesi zorunlu",
      code: "katkı süreci (CLA) ve modül pazaryeri standartları",
      test: "yayın öncesi lisans/sır/güvenlik kapıları yeşil olmalı",
      dep: "kamuya açılış kademeli (önce çekirdek, sonra ekosistem)",
      integ: "sus-lisans ve dx-marketplace ile hizalı",
      ai: "AI katkı/sır riski özeti önerir; açılış kararını insan verir",
      owasp: "A08 tedarik zinciri: açık kaynak yayını imza/SBOM ile",
      mu: "Faz 7 platformun topluluk ekosistemine açılışını tanımlar",
    },
  ),
  "build-dogfooding-kanban": D(
    "Dogfooding Kanban",
    "Dogfooding — Platform Kendini Kanban/Waterfall Aracıyla Yönetir: inşa yol haritasını kendi Project (PMS) app'iyle yönetir",
    {
      kap: "platformun kendi yol haritasını kendi araçlarıyla yönetmesini (dogfooding) tanımlar",
      code: "aynı veri kanban ve waterfall görünümünü besler (tek kaynak)",
      test: "dogfooding görünümü gerçek görev verisiyle tutarlı mı doğrulanır",
      integ: "board (tahta) ve build-sequence ile aynı veriyi paylaşır",
      ai: "AI görev dengesizliği/darboğaz önerir; planlama kararını ekip verir",
      mu: "Dogfooding platformu kendi gerçek kullanıcısı yapar",
    },
  ),
  "build-iterasyon-ritueli": D(
    "İterasyon Ritüeli",
    "Üç Kişilik İterasyon Ritüeli — Üret, Eleştir, İşlet: görev seçimi, rol rotasyonu, Bitti Tanımı, hata kurtarma, kanıt paketi",
    {
      kap: "üç kişilik ekibin üret-eleştir-işlet döngüsünü ve rol rotasyonunu tanımlar",
      sec: "üreten ≠ eleştiren (görev ayrılığı); bağımsız review zorunlu",
      code: "her iterasyon Bitti-Tanımı (DoD) ve kanıt paketiyle kapanır",
      test: "iterasyon çıktısı kanıt paketi (test/review) olmadan kabul edilmez",
      integ: "edu-yetkinlik-modeli ve sus-ai-uretim-sozlesmesi ile hizalı",
      ai: "AI üretir, ayrı bir review adımı eleştirir; işletim kararını insan verir",
      mu: "İterasyon ritüeli ekibin günlük çalışma disiplinidir",
    },
  ),
  "build-risk-defteri": D(
    "Risk Defteri",
    "Risk Defteri — Erken Sinyalden Kapanış Kanıtına: olasılık, etki, erken sinyal, azaltma, sahip ve review tarihiyle yaşayan risk kaydı",
    {
      kap: "riskleri olasılık/etki/erken-sinyal/azaltma/sahip alanlarıyla yaşayan kayıt yapar",
      sec: "güvenlik riskleri de defterde; azaltma ve sahip atanır",
      code: "her risk yapılandırılmış kayıt; review tarihiyle güncellenir",
      test: "her açık riskin bir azaltma planı ve sahibi var mı denetlenir",
      integ: "build-bilinmeyen-bilinmeyenler ve enterprise-readiness ile bağlı",
      ai: "AI yeni risk/erken sinyal önerir; azaltma ve kabul kararını sahip/insan verir",
      mu: "Risk Defteri proje risklerinin yaşayan envanteridir",
    },
  ),
  "build-bilinmeyen-bilinmeyenler": D(
    "Bilinmeyen Bilinmeyenler",
    "Bilinmeyen Bilinmeyenler — Keşif ve Sınama Defteri: planın dışında kalabilen yüksek-etkili varsayımlar ve onları görünür kılacak deneyler",
    {
      kap: "gizli/yüksek-etkili varsayımları deneylerle görünür kılmayı tanımlar",
      sec: "fark edilmeyen varsayım güvenlik açığına dönüşebilir; deneyle test edilir",
      code: "her varsayım için bir doğrulayan/çürüten deney tasarlanır",
      test: "varsayım deneyle sınanır; sonuç risk defterine işlenir",
      integ: "risk defteri ve uzman denetimiyle birlikte çalışır",
      ai: "AI olası gizli varsayım/deney önerir; deney kararını ekip verir",
      mu: "Bilinmeyen bilinmeyenler defteri körlük noktalarını azaltır",
    },
  ),
  "build-uzman-denetimi": D(
    "Uzman Denetimi",
    "Uzman Denetimi — Üç Kişilik Ekibin Güvenlik Ağı: fractional senior mimar ve alan uzmanlarının zorunlu kilometre taşı review'ları",
    {
      kap: "kritik kilometre taşlarında dış uzman review'unu zorunlu kılar",
      sec: "güvenlik-kritik kararlar uzman onayından geçer (güvenlik ağı)",
      code: "review kapsamı ve kontrol listesi kilometre taşına bağlı",
      test: "uzman review kapısı geçilmeden kilometre taşı kapanmaz",
      integ: "enterprise-readiness ve risk defteriyle hizalı",
      ai: "AI ön-review/bulgu özeti önerir; nihai onayı uzman/insan verir",
      mu: "Uzman denetimi küçük ekibin kıdem açığını kapatan güvenlik ağıdır",
    },
  ),
  "deploy-yap": D(
    "Deploy Otomasyonu",
    "Deploy — 'yap' otomasyonu: tek komut → commit + push + Actions + Pages deploy (Mac → GitHub → canlı site)",
    {
      kap: "tek komutla commit→push→CI→Pages dağıtımını otomatikleştirir",
      sec: "dağıtım sırrı CI kasasında; token logda görünmez",
      code: "'yap' komutu adımları bildirimsel sıralar; idempotent",
      test: "dağıtım öncesi CI kapıları (test/tip/a11y) yeşil olmalı",
      dep: "Mac → GitHub Actions → GitHub Pages tek komutla; geri-alma tanımlı",
      eca: "push olayında Actions tetiklenir; kapı yeşilse Pages yayınlanır",
      integ: "dx-workflow ve build-sequence kapılarıyla hizalı",
      ai: "AI dağıtım adımı/hata özeti önerir; main'e push ve yayın kararını insan verir",
      owasp: "A08 bütünlük: imzalı/onaylı dağıtım hattı",
      mu: "Deploy otomasyonu yayını tek komuta indirger",
    },
  ),
  "file-layout": D("Dosya Yapısı", "Dosya / Dizin Yapısı — önerilen monorepo yapısı", {
    kap: "monorepo'nun paket/dizin sorumluluklarını ve sınırlarını tanımlar",
    code: "dizin yapısı modül sınırlarını yansıtır; sorumluluk net",
    test: "yapı kuralları (import sınırı) makineyle denetlenebilir",
    integ: "sus-boundaries (modül sınırı) ile birlikte okunur",
    ai: "AI yanlış-yerleşim/sınır ihlali önerir; yapı kararını ekip verir",
    mu: "Dosya yapısı kod tabanının haritasını verir",
  }),
  "product-mapping": D(
    "Ürün-Stack Eşlemesi",
    "İlk Dalga: 15 Ürün → Stack Mapping — hangi ürün hangi Layer 2 stack'lerini kullanır",
    {
      kap: "ilk 15 ürünü kullandıkları Layer 2 stack'lere eşler",
      code: "eşleme generated katalogdan türetilir; elle tutulmaz",
      test: "her ürünün stack bağımlılığı gerçek katalogla tutarlı mı doğrulanır",
      integ: "aday (stack/edition) ve overview ile hizalı",
      ai: "AI eksik/çelişkili stack eşlemesi önerir; ürün kapsamı kararını ekip verir",
      mu: "Ürün-stack eşlemesi ilk dalga kapsamını netleştirir",
    },
  ),
  "product-rakip-haritasi": D(
    "Rakip Haritası",
    "Rakip Haritası — Beş Ayrı Satın Alma Alternatifi: meta-model motoru, düşük-kod, kurumsal suite, genişletme ekosistemi, hazır bileşen",
    {
      kap: "platformu beş rakip kategorisine karşı konumlar",
      code: "her kategori için farklılaştırıcı bildirimsel listelenir",
      test: "konumlama iddiaları gerçek yeteneklerle tutarlı mı denetlenir",
      integ: "overview ve product-mapping ile birlikte okunur",
      ai: "AI rakip boşluğu/fırsat önerir; konumlama kararını insan verir",
      mu: "Rakip haritası pazardaki yeri ve farkı netleştirir",
    },
  ),
  "build-app-katalogu": D(
    "App Kataloğu",
    "App Kataloğu — Clone → Stack/Edition Haritası: hedef SaaS clone'larının katalog karşılıkları (hangi app hangi stack'ten, hangi edition)",
    {
      kap: "hedef SaaS clone'larını app/stack/edition karşılıklarına eşler",
      code: "katalog generated veriden türetilir (tek kaynak)",
      test: "her clone'un app/stack ataması gerçek katalogla tutarlı mı doğrulanır",
      integ: "aday (dist/edition/stack) ve product-mapping ile hizalı",
      ai: "AI eksik clone/edition önerir; katalog kararını ürün ekibi verir",
      mu: "App kataloğu hedef ürünlerin inşa haritasını verir",
    },
  ),
  "anti-patterns": D("Anti-pattern Özeti", "Anti-pattern Özeti — 24 tuzak, niyesi ve doğrusu", {
    kap: "24 yaygın tuzağı, neden ortaya çıktığını ve doğru yaklaşımı listeler",
    sec: "güvenlik anti-pattern'leri (sır gömme, geniş yetki) ve doğrusu",
    code: "her tuzak için 'yanlış → doğru' kalıbı; uygulanabilir öneri",
    test: "mümkün olan anti-pattern'ler için yakalayan lint/kapı önerilir",
    integ: "sus-llm-hata-katalogu ve felsefe ile hizalı",
    ai: "AI olası anti-pattern kullanımı işaretler; düzeltme kararını ekip verir",
    owasp: "güvenlik anti-pattern'leri OWASP riskleriyle eşleştirilir",
    mu: "Anti-pattern özeti kaçınılacak desenlerin referansıdır",
  }),
};

apply("seed-build", CONTENT);
