#!/usr/bin/env node
/** seed-landx — Faz B19. landx kümesi (8 düğüm: LandX agent-native meta-framework modül kataloğu). */
import { D, apply } from "./seed-docs-lib.mjs";

const CONTENT = {
  "app-landx": D("LandX", "Landx — agent-native meta-framework'ün 33 modüllük 6 katmanlı (L0-L5) modül kataloğu başlığı", {
    kap: "LandX katmanlarını (çekirdek→kimlik→agent runtime→yüzey→veri→operasyon) toplar",
    integ: "Frappe/Drupal/Odoo desenlerini agent-native bakışla yeniden çerçeveler",
    ai: "AI katman/modül boşluğu özeti önerir; katalog kararını mimari ekip verir",
    mu: "LandX app'i meta-framework modül kataloğunu barındırır",
  }),
  "landx-overview": D("LandX Genel Bakış", "LandX Modül Kataloğu — Genel Bakış: 33 modülün 6 katmanlı haritası, agent-native meta-framework", {
    kap: "33 modülü 6 katmana yerleştirir ve bağımlılık yönünü gösterir",
    code: "katalog tek kaynaktan; katman bağımlılığı yukarı-doğru (döngüsüz)",
    test: "her modülün katman ataması ve bağımlılığı tutarlı mı doğrulanır",
    integ: "platform layer0/layer1 kümeleriyle kavramsal hizalı",
    ai: "AI katmanlar arası eksik bağ önerir; katalog yapısı kararını ekip verir",
    mu: "Genel bakış LandX'in bütününü tek haritada verir",
  }),
  "landx-l0": D("LandX L0", "LandX L0 — Çekirdek (Kernel): K01–K05 — plugin yaşam döngüsü, declarative schema, hook bus, service container", {
    kap: "eklenti yaşam döngüsü, bildirimsel şema, hook veri yolu ve servis kabını tanımlar",
    sec: "çekirdek en kritik katman; hook/servis erişimi en-az-ayrıcalık",
    code: "bildirimsel şemadan türetme; hook bus gevşek bağlı",
    perf: "hook çağrıları düşük gecikme; servis kabı tembel çözümleme",
    eca: "eklenti kaydedildiğinde şema doğrula + hook'ları bağla",
    integ: "platform k-schema/k-bus kavramlarına karşılık gelir",
    ai: "AI eklenti şema/hook taslağı önerir; çekirdek kayıt kararını ekip verir",
    owasp: "A08 eklenti imza bütünlüğü; çekirdek değişikliği denetlenir",
    mu: "L0 LandX'in en alt çekirdek modüllerini sağlar",
  }),
  "landx-l1": D("LandX L1", "LandX L1 — Kimlik & Kiracılık: I01–I05 — multi-tenant izolasyon, user + agent identity, MFA, permission framework", {
    kap: "kullanıcı ve agent kimliği, çok-kiracılık izolasyonu ve yetki çerçevesini tanımlar",
    sec: "tenant izolasyonu RLS ile; agent kimliği de kapsamlı ve izli",
    code: "yetki değerlendirme saf; tenant bağlamı örtük taşınır",
    perf: "kimlik/yetki kararı önbellekli; MFA hassas işlemde",
    eca: "şüpheli giriş/agent eylemi olayında kilit + uyarı",
    integ: "platform k-identity/k-authz/k-tenancy ile birebir hizalı",
    ai: "AI anormal erişim deseni önerir; kimlik/yetki politikası kararını güvenlik ekibi verir",
    owasp: "A01 erişim kontrolü ve A07 kimlik doğrulama bu katmanın çekirdeği",
    mu: "L1 LandX'in kimlik ve kiracılık modüllerini sağlar",
  }),
  "landx-l2": D("LandX L2", "LandX L2 — Agent Runtime (farklılaştırıcı): A01–A11 — MCP server, tool registry, vector store, memory, prompt lib, LLM gözlemlenebilirlik, agent orkestrasyon", {
    kap: "agent çalışma zamanı: araç kayıt defteri, bellek, vektör deposu, LLM gözlemlenebilirliği",
    sec: "agent araçları yetenek-tabanlı sınırlı; sub_prompt güvenilmez girdi kabul edilir",
    code: "araç kayıt defteri tipli; agent orkestrasyonu durum-makineli",
    perf: "vektör arama indeksli; LLM çağrısı maliyet/gecikme izlenir",
    eca: "agent eylem zinciri maxChainDepth=6 ile sınırlı; aşımda durur",
    integ: "platform aiAgents politikası ve eca motoruyla hizalı",
    ai: "AI bu katmanda çalışır ama app/modül üretemez; yalnız tipli, yetkili, audit'li aksiyonlara erişir",
    owasp: "LLM Top 10: prompt enjeksiyonu ve aşırı-yetki bu katmanda ele alınır",
    mu: "L2 LandX'i agent-native yapan farklılaştırıcı modülleri sağlar",
  }),
  "landx-l3": D("LandX L3", "LandX L3 — Uygulama Yüzeyi: S01–S06 — otomatik REST API, admin UI engine, form/validation, workflow, notification, search", {
    kap: "şemadan otomatik REST API, admin UI, form, iş akışı, bildirim ve arama üretir",
    sec: "üretilen API yetki kontrolünden geçer; form doğrulaması sunucuda",
    code: "yüzeyler metadata'dan türetilir; elle tekrar yok",
    perf: "arama indeksli; liste sayfalı; bildirim asenkron",
    wcag: "üretilen admin UI ve formlar WCAG 2.2 AAA varsayılanı taşır",
    eca: "kayıt olayında bildirim/iş akışı tetiklenir",
    integ: "platform Surface/Workflow sözleşmeleriyle kavramsal hizalı",
    ai: "AI yüzey/form taslağı önerir; yayın kararını ekip verir",
    mu: "L3 LandX'in uygulama yüzeyi (API/UI) modüllerini sağlar",
  }),
  "landx-l4": D("LandX L4", "LandX L4 — Veri & Uyumluluk: D01–D03 — audit log, PII governance, KVKK/GDPR/SOC2 çerçevesi", {
    kap: "denetim günlüğü, PII yönetişimi ve uyumluluk (KVKK/GDPR/SOC2) çerçevesini tanımlar",
    sec: "PII sınıflandırılır, maskelenir; denetim günlüğü değişmez (immutable)",
    code: "PII etiketi şemada taşınır; uyumluluk kuralı bildirimsel",
    perf: "denetim günlüğü append-only, sorgu için ayrı indeks",
    eca: "PII erişimi/saklama süresi olayında uyumluluk akışı tetiklenir",
    integ: "platform crosscut (privacy/compliance) kümesiyle hizalı",
    ai: "AI PII sınıflandırma/uyum boşluğu önerir; veri-hakları kararını sorumlu insan verir",
    owasp: "A02 veri koruma ve A09 loglama bu katmanın çekirdeği",
    mu: "L4 LandX'in veri yönetişimi ve uyumluluk modüllerini sağlar",
  }),
  "landx-l5": D("LandX L5", "LandX L5 — Operasyon & Marketplace: O01–O03 — gözlemlenebilirlik/SLO, plugin marketplace, plugin güvenlik incelemesi & sandbox sertifikasyonu", {
    kap: "gözlemlenebilirlik/SLO, eklenti pazaryeri ve sandbox güvenlik sertifikasyonunu tanımlar",
    sec: "marketplace eklentisi imza + güvenlik incelemesi + sandbox sertifikasından geçer",
    code: "SLO bildirimsel; eklenti sürümleme semver",
    perf: "SLO/metri̇k toplama düşük ek-yük; uyarı eşikli",
    eca: "SLO ihlali/güvenlik bulgusu olayında uyarı + eklenti işaretleme",
    integ: "platform dx-marketplace ve gözlemlenebilirlik kavramlarıyla hizalı",
    ai: "AI eklenti güvenlik riski/SLO ihlali özeti önerir; sertifikasyon kararını ekip verir",
    owasp: "A06 savunmasız bileşen taraması ve A08 tedarik zinciri bu katmanda",
    mu: "L5 LandX'in operasyon ve pazaryeri modüllerini sağlar",
  }),
};

apply("seed-landx", CONTENT);
