#!/usr/bin/env node
/** seed-sus — Faz B19. sus kümesi (21 düğüm: sürdürülebilirlik mekanizmaları + lisans + 3 x-kırılım). */
import { D, apply, xdim } from "./seed-docs-lib.mjs";

const CONTENT = {
  "app-sus": D(
    "Platform Yetenekleri",
    "Platform Yetenekleri (Sürdürülebilirlik) — mimariyi onlarca yıl yaşatan mekanizmaların kataloğu",
    {
      kap: "bitemporal kayıt, sözleşme kapısı, declarative türetme, lisans gibi sürdürülebilirlik mekanizmalarını toplar",
      integ: "kararlar (ADR) ve platform katmanlarıyla doğrudan ilişkili",
      ai: "AI mekanizma boşluğu/risk özeti önerir; benimseme kararını mimari ekip verir",
      mu: "Platform Yetenekleri app'i uzun-ömür mekanizmalarını barındırır",
    },
  ),
  "app-sus-x-atom": xdim(
    "SürdürÜlebilirlik Atomu",
    "bölünemez bir sürdürülebilirlik ilkesinin örnek kırılımı",
  ),
  "app-sus-x-element": xdim(
    "Sürdürülebilirlik Elementi",
    "tek bir sürdürülebilirlik kuralının örnek kırılımı",
  ),
  "app-sus-x-molecule": xdim(
    "Sürdürülebilirlik Molekülü",
    "birkaç sürdürülebilirlik kuralını birleştiren örnek kırılım",
  ),

  "sus-overview": D(
    "Sürdürülebilirlik Haritası",
    "Sürdürülebilirlik haritası — neden mekanizma? Olgun mimariyi 30-50 yıl yaşatan iyi tasarım değil mekanizmadır (Linux/Stripe)",
    {
      kap: "uzun-ömrü sağlayan mekanizmaları (sözleşme kararlılığı, türetme, audit) tek haritada toplar",
      code: "her ilke somut mekanizmaya bağlanır; soyut slogan değil",
      test: "her mekanizma doğrulanabilir bir kapıyla temsil edilir mi denetlenir",
      integ: "tüm sus-* sayfalarının giriş/özet düğümü",
      ai: "AI eksik mekanizma önerir; mimari yön kararını insan verir",
      mu: "Genel bakış sürdürülebilirlik mekanizmalarının gerekçesini verir",
    },
  ),
  "sus-actions": D(
    "Tipli Aksiyon Yüzeyi",
    "Tipli kinetik aksiyon yüzeyi (AI için) — Palantir Ontology: AI ham tabloya değil tipli, yetkili, audit'li action'lara erişir",
    {
      kap: "AI ve kullanıcı eylemlerini tipli, yetkilendirilmiş, denetlenen action'lara kısıtlar",
      sec: "AI ham veriye değil yalnız yetkili action'a erişir; her action audit'lenir",
      code: "action'lar tipli sözleşme; yan etki action sınırında",
      eca: "action çağrısı yetki+şema doğrulamadan geçer, geçersizse reddedilir",
      integ: "platform typed-actions ve aiAgents politikasıyla birebir hizalı",
      ai: "AI yalnız tanımlı tipli action'ları çağırabilir; yeni action ve yetki kararını insan verir",
      owasp: "A01 erişim kontrolü ve A04 güvenli-tasarım bu mekanizmanın özü",
      mu: "Tipli aksiyon yüzeyi AI'ın güvenli etki alanını tanımlar",
    },
  ),
  "sus-ai-uretim-sozlesmesi": D(
    "AI Üretim Sözleşmesi",
    "AI Üretim Sözleşmesi — Üreten Onaylayamaz: kaynak, varsayım, bağımsız eleştiri ve deterministik kapılarla AI eşliğinde geliştirme",
    {
      kap: "AI üretimini kaynak+varsayım+bağımsız review+deterministik kapı disiplinine bağlar",
      sec: "üreten onaylayamaz (görev ayrılığı); AI main'e doğrudan yazamaz",
      code: "deterministik kapılar (test/tip/lint) AI çıktısını süzер",
      test: "AI çıktısı bağımsız review ve test-önce kapıdan geçmeden kabul edilmez",
      integ: "adr-0014 (karar/gereksinim ayrımı) ve felsefe ile hizalı",
      ai: "AI üretir ve PR açabilir; merge ve onay kararını insan verir (üreten onaylayamaz)",
      owasp: "A04 güvenli-tasarım: insan onayı zorunlu kapı",
      mu: "AI Üretim Sözleşmesi güvenli AI-eşli geliştirmenin çerçevesidir",
    },
  ),
  "sus-bc-policy": D(
    "Sözleşme Kapısı",
    "Sözleşme kapısı — 'Don't break userspace' (Linus Torvalds 1 numaralı kuralı): bir değişiklik kullanıcı programını kırıyorsa hata çekirdektedir",
    {
      kap: "geriye uyumluluğu mutlak kural yapar; sözleşme kırılması = regresyon",
      sec: "sözleşme değişikliği sürümlü; sessiz kırıcı değişiklik yasak",
      code: "kırıcı değişiklik yerine genişlet-daralt (expand-contract) deseni",
      test: "sözleşme (conformance) testi kırılırsa değişiklik reddedilir",
      integ: "sus-conformance ve sus-versioning ile birlikte çalışır",
      ai: "AI olası kırıcı değişikliği işaretler; kuralın istisnası kararını insan verir",
      owasp: "A08 bütünlük: sözleşme kararlılığı kullanıcıyı korur",
      mu: "Sözleşme kapısı geriye uyumluluğu makineyle zorlar",
    },
  ),
  "sus-bitemporal": D(
    "Bitemporal Kayıt",
    "Bitemporal immutable kayıt — tek doğruluk (XTDB): valid_time + system_time otomatik; audit/time-travel/KVKK bedava",
    {
      kap: "her kaydı geçerlilik-zamanı ve sistem-zamanı ile saklar; geçmiş değişmez",
      sec: "değişmez kayıt audit ve KVKK kanıtını yapısal sağlar",
      code: "güncelleme yeni sürüm ekler; eski sürüm silinmez",
      perf: "zaman-sorgusu indeksli; geçmiş sorgu ayrı yoldan",
      eca: "kayıt değiştiğinde yeni bitemporal sürüm yazılır",
      integ: "k-archetype-storage ve audit kavramlarıyla hizalı",
      ai: "AI zaman-içi anomali önerir; veri düzeltme kararını insan verir (geçmiş yine korunur)",
      owasp: "A09 loglama/izlenebilirlik bitemporal yapıyla güçlenir",
      mu: "Bitemporal kayıt tek-doğruluk ve zaman-yolculuğu sağlar",
    },
  ),
  "sus-boundaries": D(
    "Modül Sınırı Kapısı",
    "Makine-zorlamalı modül sınırı (CI kapısı) — Shopify Packwerk: 2.8M satırlık monolit modüler kalmasını CI'da PR reddiyle sağlar",
    {
      kap: "modüller arası izinsiz bağımlılığı CI'da PR reddederek engeller",
      sec: "sınır ihlali = mimari sızıntı; CI kapısı bloklar",
      code: "modül sınırı bildirimsel tanımlı; ihlal makineyle yakalanır",
      test: "sınır kapısı yeşil değilse PR merge edilemez",
      eca: "PR sınır ihlali içeriyorsa otomatik reddedilir",
      integ: "build-sequence ve dx-workflow kapılarıyla hizalı",
      ai: "AI olası sınır ihlali önerir; sınır tanımı değişikliğini mimari ekip onaylar",
      owasp: "A04 güvenli-tasarım: modülerlik makineyle korunur",
      mu: "Modül sınırı kapısı monolitin modüler kalmasını sağlar",
    },
  ),
  "sus-codemod": D(
    "Otomatik Upgrade",
    "Otomatik upgrade — kendini-yükselten döngü (Drupal Rector + AI): her deprecation bir codemod kuralı olur, AI eski kodu yeniden yazar",
    {
      kap: "deprecation'ları codemod kurallarına çevirip kod tabanını otomatik günceller",
      sec: "codemod değişikliği review+test'ten geçer; kör uygulanmaz",
      code: "her deprecation → tekrar-uygulanabilir codemod kuralı",
      test: "codemod sonrası tüm testler yeşil olmalı; değilse geri alınır",
      eca: "deprecation tespit edilince codemod önerisi üretilir (insan onaylı uygular)",
      integ: "sus-versioning ve dx-workflow ile birlikte çalışır",
      ai: "AI codemod kuralı ve dönüşüm önerir; uygulama ve merge kararını insan verir",
      owasp: "A06 savunmasız bileşen: güncel kalmayı otomatikleştirir",
      mu: "Otomatik upgrade kod tabanını kendini-yenileyen kılar",
    },
  ),
  "sus-conformance": D(
    "Sözleşme Koşumu",
    "Test-önce sözleşme koşumu — PostgreSQL merge-gate disiplini + Stripe-mock + Hypothesis property-based testing",
    {
      kap: "sözleşmeyi (API/şema davranışı) test-önce ve property-based doğrular",
      sec: "sözleşme dışı davranış kabul edilmez; merge-gate bloklar",
      code: "conformance testi sözleşmeyle eş-üretilir (tek kaynak)",
      test: "property-based test + mock ile sözleşme geniş girdi uzayında sınanır",
      eca: "sözleşme testi kırılırsa merge engellenir",
      integ: "sus-bc-policy ve dx-workflow kapılarıyla hizalı",
      ai: "AI sözleşme testi senaryosu önerir; sözleşme tanımı kararını ekip verir",
      owasp: "A04 güvenli-tasarım: davranış sözleşmeyle sabitlenir",
      mu: "Sözleşme koşumu davranış kararlılığını test-önce garanti eder",
    },
  ),
  "sus-declarative": D(
    "Declarative Türetme",
    "Declarative resource'tan türetme (Ash Framework, Elixir): tek resource tanımından DB+API+authz+state machine türetilir",
    {
      kap: "tek bildirimsel tanımdan veritabanı, API, yetki ve durum makinesini türetir",
      sec: "yetki kuralı tanımda; her yüzey aynı kuraldan türer (tutarlılık)",
      code: "tek doğruluk kaynağı; elle tekrar yok (DRY)",
      perf: "türetilmiş katman önbeklenir; tanım değişince yeniden üretilir",
      eca: "tanım değiştiğinde bağlı yüzeyler yeniden türetilir",
      integ: "ArcheType (k-schema) declarative türetme felsefesiyle aynı",
      ai: "AI resource tanımı taslağı önerir; tanım kararını ekip verir",
      owasp: "A04 güvenli-tasarım: tek tanım → tutarlı yetki",
      mu: "Declarative türetme tek tanımdan tüm katmanı üretir",
    },
  ),
  "sus-durable": D(
    "Durable Execution",
    "Postgres-native durable execution (DBOS): ayrı orkestratör yok; workflow durumu mevcut Postgres'te checkpoint'lenir",
    {
      kap: "uzun iş akışı durumunu veritabanında checkpoint'leyerek dayanıklı çalıştırır",
      sec: "workflow durumu kalıcı; çökme sonrası kaldığı yerden güvenli devam",
      code: "ayrı orkestratör altyapısı yok; mevcut PostgreSQL kullanılır",
      perf: "checkpoint maliyeti düşük; gereksiz altyapı yok",
      eca: "uzun akış adımı tamamlandığında durum checkpoint'lenir (idempotent)",
      integ: "scale kümesi (saga/outbox) ve eca motoruyla hizalı",
      ai: "AI akış darboğazı önerir; workflow tasarımı kararını ekip verir",
      owasp: "A04 güvenli-tasarım: dayanıklı durum kaybı önlenir",
      mu: "Durable execution ek altyapısız dayanıklı iş akışı sağlar",
    },
  ),
  "sus-metadata": D(
    "Her-Şey-Metadata",
    "Her-şey-metadata (introspectable kayıt) — ServiceNow: tablo, rol, workflow, API her şey introspectable kayıt; governance + audit",
    {
      kap: "tablo/rol/workflow/API'yi sorgulanabilir metadata kaydı olarak tutar",
      sec: "introspectable yapı governance ve audit'i kolaylaştırır",
      code: "yapı verisi de veri; runtime'da sorgulanır",
      perf: "metadata önbellekli; introspection hızlı",
      eca: "metadata değiştiğinde bağlı yüzeyler güncellenir",
      integ: "k-schema (metadata engine) ile birebir hizalı",
      ai: "AI metadata tutarsızlığı önerir; metadata değişikliği kararını ekip verir",
      owasp: "A09 loglama: introspectable yapı denetimi güçlendirir",
      mu: "Her-şey-metadata yönetişim ve audit'i yapısal sağlar",
    },
  ),
  "sus-timi": D(
    "TIMI Stabil Arayüz",
    "ArcheType → TIMI stabil arayüz (IBM i, 1988-): TIMI sayesinde 35+ yıl 25 işlemci nesli üzerinde aynı uygulama çalışır",
    {
      kap: "uygulamayı donanım/altyapıdan soyutlayan stabil ara katman tanımlar",
      sec: "stabil arayüz alt katman değişse de uygulamayı korur",
      code: "ArcheType = stabil sözleşme; altyapı arkada değişebilir",
      perf: "alt katman optimize edilebilir; üst sözleşme sabit kalır",
      eca: "altyapı değişimi üst sözleşmeyi tetiklemez (yalıtım)",
      integ: "ArcheType depolama (hibrit) ve sus-versioning ile hizalı",
      ai: "AI alt katman iyileştirme önerir; stabil arayüz kararını mimari ekip verir",
      owasp: "A08 bütünlük: stabil arayüz uzun-ömrü korur",
      mu: "TIMI deseni uygulamayı altyapıdan bağımsız uzun-ömürlü kılar",
    },
  ),
  "sus-versioning": D(
    "Tarih-Tabanlı Versiyonlama",
    "Tarih-tabanlı versiyonlama + dönüşüm katmanı (Stripe, 2011'den beri 14 yıl uyumlu): çekirdek tek-sürüm yazar, dönüşüm eski sürüme uyarlar",
    {
      kap: "API'yi tarih-tabanlı sürümler; çekirdek tek sürüm, dönüşüm katmanı eskiye uyarlar",
      sec: "eski istemci kırılmaz; sürüm geçişi denetimli",
      code: "çekirdek tek-sürüm yazar (sadelik); dönüşüm dışarıda",
      perf: "dönüşüm katmanı ince; çekirdek karmaşıklığı artmaz",
      eca: "yeni sürüm yayınlandığında dönüşüm kuralları eklenir",
      integ: "sus-bc-policy ve adr-0013 (MD sözleşme) ile hizalı",
      ai: "AI sürüm farkı/dönüşüm kuralı önerir; sürüm politikası kararını ekip verir",
      owasp: "A08 bütünlük: sürüm uyumu kullanıcıyı korur",
      mu: "Tarih-tabanlı versiyonlama uzun süreli API uyumunu sağlar",
    },
  ),
  "sus-lisans": D(
    "Lisans Mimarisi",
    "Lisans Mimarisi — AGPL Kernel + MIT SDK + CLA: bulut-devi ve parazit-pazaryeri senaryolarına karşı open-core katmanlı strateji",
    {
      kap: "çekirdek AGPL, SDK MIT, katkı için CLA ile katmanlı lisans stratejisi tanımlar",
      sec: "lisans seçimi kötüye kullanım (bulut-devi) riskini azaltır",
      code: "katman bazında lisans; çekirdek ile SDK ayrı",
      test: "her paketin lisans başlığı/uyumu CI'da denetlenir",
      integ: "sus-lisans-tr-hukuk ve sus-lisans-vakalar ile birlikte okunur",
      ai: "AI lisans uyum boşluğu önerir; lisans kararını insan/hukuk verir",
      owasp: "A08 tedarik zinciri: lisans uyumu bağımlılık riskini yönetir",
      mu: "Lisans Mimarisi sürdürülebilir açık-çekirdek modelini tanımlar",
    },
  ),
  "sus-lisans-tr-hukuk": D(
    "Lisans Hukuku (TR)",
    "Lisans Hukuku — Türkiye ve Uluslararası Uygulanabilirlik: copyleft'in FSEK temeli, m.52 yazılı-şekil riski, emsal içtihat (Welte)",
    {
      kap: "copyleft lisansların TR (FSEK) ve uluslararası uygulanabilirliğini analiz eder",
      sec: "lisans hukuki dayanağı netleşmezse kullanım riski doğar",
      code: "lisans metni ve FSEK m.52 yazılı-şekil gereği belgelenir",
      test: "lisans uyumu hukuki kontrol listesiyle gözden geçirilir",
      integ: "sus-lisans ve sus-lisans-vakalar ile hukuki bütünlük",
      ai: "AI içtihat/emsal özeti önerir; hukuki yorum kararını uzman/insan verir",
      owasp: "A08 uyum: hukuki dayanak tedarik zinciri güvenini destekler",
      mu: "Lisans Hukuku (TR) lisans seçiminin hukuki zeminini verir",
    },
  ),
  "sus-lisans-vakalar": D(
    "Lisans Vakaları",
    "Lisans Vakaları ve Karar Matrisi: Grafana'nın AGPL geçişi, Redis/Elastic krizleri ders ders",
    {
      kap: "sektörün lisans krizlerini ve çıkarılan dersleri karar matrisine dönüştürür",
      sec: "yanlış lisans = çatallanma/itibar riski; vakalardan ders alınır",
      code: "her vaka için karar matrisi girdisi (durum→öneri)",
      test: "karar matrisi mevcut lisans seçimiyle çelişmiyor mu denetlenir",
      integ: "sus-lisans ve sus-lisans-tr-hukuk ile birlikte okunur",
      ai: "AI vaka benzerliği/risk önerir; lisans stratejisi kararını insan verir",
      owasp: "A08 tedarik zinciri: lisans riski yönetimi",
      mu: "Lisans Vakaları geçmiş krizlerden öğrenme matrisidir",
    },
  ),
  "sus-llm-hata-katalogu": D(
    "LLM Hata Kataloğu",
    "LLM Hata Kataloğu — Sınıflar ve Mevcut Önlemler: AI üretilen kodun tekrar eden hata sınıfları ve her birinin bu projedeki kapı/önlemi",
    {
      kap: "AI üretilen kodun tekrar eden hata sınıflarını ve önlemlerini kataloglar",
      sec: "her hata sınıfı bir kapı/önlemle eşleştirilir; sessiz geçiş yok",
      code: "hata sınıfı → mevcut kapı (test/tip/lint/review) eşlemesi",
      test: "her hata sınıfı için bir yakalayan test/kapı var mı denetlenir",
      integ: "sus-ai-uretim-sozlesmesi ve dx-workflow kapılarıyla hizalı",
      ai: "AI yeni hata sınıfı/önlem önerir; kapı ekleme kararını ekip verir",
      owasp: "A04 güvenli-tasarım: bilinen AI hataları kapıyla önlenir",
      mu: "LLM Hata Kataloğu AI üretiminin risk envanteridir",
    },
  ),
};

apply("seed-sus", CONTENT);
