#!/usr/bin/env node
/** seed-edu — Faz B19. edu kümesi (31 eğitim ünitesi: yazılım temelleri → üretim işletimi). */
import { D, apply } from "./seed-docs-lib.mjs";

const CONTENT = {
  "app-edu": D("Eğitim", "Eğitim — yazılım temellerinden üretim işletimine 25+ ünitelik müfredat kümesi", {
    kap: "veri/tip, ArcheType, veritabanı, API, güvenlik, deploy gibi temel üniteleri toplar",
    integ: "egitim (rehberler) ve build (inşa sırası) ile faz haritası üzerinden bağlı",
    ai: "AI ünite alıştırması önerir; öğrenme yolu kararını ekip verir",
    mu: "Eğitim app'i kavramsal müfredatı barındırır",
  }),
  "edu-overview": D("Eğitim Yaklaşımı", "Eğitim yaklaşımı — bu döküman nasıl okunur: tüm doküman bir eğitim materyali; yöntem burada, konular sonraki kümelerde", {
    kap: "müfredatın nasıl okunacağını ve ünite-faz ilişkisini açıklar",
    test: "her ünitenin bir kanıt/alıştırmayla kapandığı ilkesini koyar",
    integ: "edu-faz-haritasi ve yetkinlik modeliyle hizalı",
    ai: "AI okuma sırası önerir; müfredat kararını ekip verir",
    mu: "Eğitim yaklaşımı müfredatın kullanım kılavuzudur",
  }),
  "edu-u01": D("Ünite 01", "Yazılım nedir? — temel zihinsel model: kod, derleyici, runtime, framework, monolit, meta-framework", {
    kap: "kod→derleyici→runtime zincirini ve framework/meta-framework farkını öğretir",
    code: "monolit ile meta-framework arasındaki yapısal fark açıklanır",
    test: "kavram kontrolü: küçük bir programın derleme/çalıştırma adımı",
    integ: "sonraki tüm ünitelerin kavramsal temeli",
    ai: "AI kavramı örnekle açıklar; öğrenmenin doğrulanmasını öğrenci yapar",
    mu: "Ünite 01 yazılımın zihinsel modelini kurar",
  }),
  "edu-u02": D("Ünite 02", "Veri ve Tipler — atomik öncesi temel: bit'ten Decimal'e, harften UTF-8'e; neden Decimal (float değil)", {
    kap: "verinin saklanışını, tip kavramını ve Decimal/float farkını öğretir",
    sec: "yanlış tip (float para) finansal hata doğurur; Decimal zorunlu",
    code: "tip seçimi doğruluğu belirler; UTF-8 metin temeli",
    test: "float yuvarlama hatası ve Decimal doğruluğu örnekle sınanır",
    integ: "atomic (Money/değer nesneleri) ünitesinin önkoşulu",
    ai: "AI tip seçimi örneği verir; doğru tip kararını öğrenci/geliştirici verir",
    mu: "Ünite 02 doğru veri tipi temelini kurar",
  }),
  "edu-u02b": D("Ünite 02b", "Para, Tarih ve Zaman Dilimi — gizli karmaşıklık: yüzeyde basit, derinde tuzak olan iki konu", {
    kap: "para tipi ve zaman/zaman-dilimi tuzaklarını derinleştirir",
    sec: "zaman dilimi hatası randevu/log/audit'i bozar; para hatası finansal risk",
    code: "para tam-sayı kuruş; zaman UTC sakla, yerelde göster",
    test: "zaman dilimi geçişi ve para yuvarlama kenar durumları sınanır",
    integ: "edu-u21 (money+tax) ile derinleşir; atomic ile bağlı",
    ai: "AI tuzak örneği gösterir; tasarım kararını geliştirici verir",
    mu: "Ünite 02b para/zaman gizli karmaşıklığını açar",
  }),
  "edu-u03": D("Ünite 03", "ArcheType ile Model — anlatımsal giriş: tip dizisi tanımlarsın, framework DB tablosu/REST/form/audit'i otomatik üretir", {
    kap: "bildirimsel ArcheType tanımından otomatik türetme fikrini öğretir",
    code: "tek tanım → DB+API+form+audit (DRY); elle tekrar yok",
    sec: "yetki ve audit tanımdan türer; tutarlılık yapısal",
    test: "bir ArcheType tanımından üretilen yüzeyler örnekle gösterilir",
    integ: "k-schema/declarative türetme ve edu-u25 ile bağlı",
    ai: "AI bildirimsel model taslağı önerir; tip dizisi tanımı kararını geliştirici verir",
    mu: "Ünite 03 meta-framework'ün çekirdek fikrini kurar",
  }),
  "edu-u04": D("Ünite 04", "Veritabanı Temelleri — ArcheType'tan önce: PostgreSQL, tablo, kolon, indeks, FK, transaction, ACID, normalize/denormalize", {
    kap: "ilişkisel veritabanı temellerini (tablo/indeks/FK/transaction/ACID) öğretir",
    sec: "parametreli sorgu ile SQL injection önlenir; FK bütünlük sağlar",
    code: "normalize tasarım tekrarı önler; indeks sorguyu hızlandırır",
    perf: "indeks ve sorgu planı (EXPLAIN) ile yavaş sorgu bulunur",
    test: "transaction ve ACID davranışı örnekle sınanır",
    integ: "edu-u04b (veri tasarımı) ve k-archetype-storage ile bağlı",
    ai: "AI sorgu/indeks önerir; şema kararını geliştirici verir",
    owasp: "A03 injection: parametreli sorgu bu ünitede öğretilir",
    mu: "Ünite 04 ilişkisel veritabanı temelini kurar",
  }),
  "edu-u04b": D("Ünite 04b", "Veri Tasarımı — normalleştirme ve ilişkiler: doğru tablo yapısı 3 ay sonra hayat kurtarır", {
    kap: "normalleştirme, ilişki türleri ve doğru tablo tasarımını derinleştirir",
    code: "normalleştirme tekrarı/anomaliyi önler; ilişki kardinalitesi netleşir",
    perf: "aşırı normalleştirme join maliyeti; bilinçli denormalize dengesi",
    test: "tasarım kararları örnek veriyle (anomali testi) sınanır",
    integ: "edu-u04 üzerine kurulur; ArcheType ilişkileriyle bağlı",
    ai: "AI tasarım/ilişki önerir; veri modeli kararını geliştirici verir",
    mu: "Ünite 04b sağlam veri tasarımı disiplinini verir",
  }),
  "edu-u05": D("Ünite 05", "API: REST ve GraphQL — pratik anlatım: HTTP istek-cevap, method, status, JSON, REST kuralları, GraphQL farkı, idempotent, versioning", {
    kap: "REST ve GraphQL temellerini ve idempotent/versioning kavramını öğretir",
    sec: "API yetki kontrolü ve girdi doğrulama her uçta zorunlu",
    code: "idempotent metot tekrar-güvenli; versioning geriye uyum sağlar",
    perf: "GraphQL aşırı-çekim/N+1 riski; REST sayfalama",
    test: "idempotency ve status kodu davranışı örnekle sınanır",
    integ: "dx-api-gateway ve sus-versioning ile bağlı",
    ai: "AI API sözleşmesi taslağı önerir; sözleşme kararını ekip verir",
    owasp: "A01 erişim kontrolü ve A03 injection API katmanında öğretilir",
    mu: "Ünite 05 API tasarım temelini kurar",
  }),
  "edu-u06": D("Ünite 06", "Multi-tenancy — bir kod, çok müşteri: tenant izolasyonu, row-level (RLS) vs schema-per-tenant", {
    kap: "çok-kiracılık modellerini (RLS vs schema) ve izolasyonu öğretir",
    sec: "tenant izolasyonu RLS ile veritabanı düzeyinde; çapraz-tenant sızıntı önlenir",
    code: "tenant_id her sorguda kapsamlı; bağlam örtük taşınır",
    perf: "tenant_id bileşik indeksin ilk kolonu; büyük tenant sharding",
    test: "çapraz-tenant erişim negatif testle sınanır",
    integ: "k-tenancy (RLS) ve edu-u07 ile bağlı",
    ai: "AI izolasyon deseni önerir; tenancy modeli kararını mimari ekip verir",
    owasp: "A01 erişim kontrolü: tenant izolasyonu bu ünitede merkez",
    mu: "Ünite 06 çok-kiracılık temelini kurar",
  }),
  "edu-u07": D("Ünite 07", "Yetkilendirme & Güvenlik: identity, session, RBAC/ABAC, audit, KVKK, encryption at rest + transit", {
    kap: "kimlik, oturum, RBAC/ABAC, audit ve şifreleme temellerini öğretir",
    sec: "güvenli-varsayılan deny; veri durağan ve aktarımda şifreli",
    code: "yetki kararı merkezi motor; oturum kısa ömürlü token",
    test: "yetki matrisi ve yetki yükseltme negatif testle sınanır",
    integ: "k-identity/k-authz ve crosscut (privacy) ile bağlı",
    ai: "AI politika boşluğu önerir; yetki politikası kararını güvenlik ekibi verir",
    owasp: "A01 erişim kontrolü ve A07 kimlik doğrulama bu ünitenin özü",
    mu: "Ünite 07 güvenlik ve yetki temelini kurar",
  }),
  "edu-u08": D("Ünite 08", "Event Bus & Outbox: senkron vs asenkron, event-driven, transactional outbox, idempotency, DLQ", {
    kap: "olay-güdümlü mimari, transactional outbox ve idempotency'i öğretir",
    sec: "olay mesajı tenant damgalı; sahte olay reddedilir",
    code: "transactional outbox tutarlılık; idempotent tüketici tekrar-güvenli",
    perf: "asenkron işleme sırt basıncı; DLQ ile başarısız mesaj izolasyonu",
    test: "idempotent tüketim ve DLQ davranışı sınanır",
    integ: "k-bus (event bus) ve scale (outbox/saga) ile bağlı",
    ai: "AI akış darboğazı önerir; topoloji kararını ekip verir",
    owasp: "A04 güvenli-tasarım: idempotent + DLQ ile dayanıklılık",
    mu: "Ünite 08 olay-güdümlü mimari temelini kurar",
  }),
  "edu-u09": D("Ünite 09", "Modül Mimarisi: manifest, registry, hook, semver, marketplace, contract test, sandboxing", {
    kap: "modül manifest'i, kayıt defteri, hook ve sandboxing'i öğretir",
    sec: "modül imzalı; sandbox izolasyonu; izin talebi en-az-ayrıcalık",
    code: "manifest sürümlü (semver); contract test sözleşmeyi korur",
    test: "modül contract testi ve semver uyumu sınanır",
    integ: "k-mod-l/k-plugin ve dx-marketplace ile bağlı",
    ai: "AI modül bağımlılık çakışması önerir; kayıt kararını ekip verir",
    owasp: "A08 bütünlük: modül imza/sandbox bu ünitede",
    mu: "Ünite 09 modüler mimari temelini kurar",
  }),
  "edu-u10": D("Ünite 10", "Deploy & Operations: Git, CI/CD, GitHub Actions, Hetzner, observability, on-call, runbook, incident", {
    kap: "Git, CI/CD, dağıtım, gözlemlenebilirlik ve olay yönetimini öğretir",
    sec: "dağıtım sırrı kasada; main'e push yetki+kapı kontrollü",
    code: "CI artımlı; dağıtım kademeli ve geri-alınabilir",
    perf: "gözlemlenebilirlik (metrik/iz/log) ile darboğaz görünür",
    test: "CI kapıları yeşil olmadan dağıtım yapılmaz",
    dep: "GitHub Actions → Hetzner/Pages; runbook ile olay kurtarma",
    integ: "dx-workflow ve deploy-yap ile bağlı",
    ai: "AI olay/log özeti önerir; dağıtım ve müdahale kararını insan verir",
    mu: "Ünite 10 dağıtım ve operasyon temelini kurar",
  }),
  "edu-u11": D("Ünite 11", "Hata Yönetimi — try/catch'ten DLQ'ya: üretim çöküşlerinin önemli kısmı kötü hata yönetiminden", {
    kap: "hata yakalama, kurtarma ve DLQ desenlerini öğretir",
    sec: "hata mesajı hassas bilgi sızdırmamalı; içeride detay, dışarıda genel",
    code: "hata türleri ayrılır; geçici hata yeniden-denenir, kalıcı hata DLQ'ya",
    test: "hata yolları ve kurtarma senaryoları sınanır",
    integ: "edu-u08 (DLQ) ve edu-u13 (log) ile bağlı",
    ai: "AI hata deseni/kök-neden önerir; düzeltme kararını geliştirici verir",
    owasp: "A09 loglama: hata izlenebilirliği bu ünitede",
    mu: "Ünite 11 dayanıklı hata yönetimi disiplinini verir",
  }),
  "edu-u12": D("Ünite 12", "Migration Disiplini — şema evrimi: çalışan üretimde tablo değiştirmek; expand-contract yöntemi", {
    kap: "güvenli şema göçü (expand-contract) ve geri-alma disiplinini öğretir",
    sec: "göç sırasında veri kaybı/erişim kesintisi önlenir",
    code: "expand-contract: önce ekle, sonra geçir, sonra kaldır (kırıcı değil)",
    test: "göç dry-run + geri-alma + veri bütünlüğü sınanır",
    integ: "adr-0016 (ChangeSet) ve sus-bc-policy ile bağlı",
    ai: "AI göç planı/veri-etki özeti önerir; göç kararını ekip onaylar",
    owasp: "A08 bütünlük: göç sürümlü ve geri-alınabilir",
    mu: "Ünite 12 güvenli şema evrimi disiplinini verir",
  }),
  "edu-u13": D("Ünite 13", "Log Disiplini — yazılımın günlüğü: çökmüş üretimi log olmadan çözmek karanlıkta iğne aramaktır", {
    kap: "yapılandırılmış log, seviye ve korelasyon disiplinini öğretir",
    sec: "log'da PII/sır maskelenir; hassas veri yazılmaz",
    code: "yapılandırılmış (JSON) log + korelasyon kimliği; seviyeli",
    perf: "aşırı log maliyeti; örnekleme (sampling) dengesi",
    test: "kritik olayların loglandığı ve PII'nin maskelendiği sınanır",
    integ: "edu-u11 (hata) ve audit (layer1) ile bağlı",
    ai: "AI log deseninden anomali önerir; müdahale kararını insan verir",
    owasp: "A09 loglama/izleme bu ünitenin merkezi",
    mu: "Ünite 13 etkili log disiplinini verir",
  }),
  "edu-u14": D("Ünite 14", "Cache ve Rate Limit — hız ve adalet: cache aynı işi 2 kez yapmamak, rate limit bir kullanıcının tüm kapasiteyi tüketmemesi", {
    kap: "önbellekleme ve hız sınırı desenlerini öğretir",
    sec: "rate limit kötüye kullanımı/DoS'u daraltır; cache yetki-duyarlı olmalı",
    code: "cache geçersizleme stratejisi; rate limit token/tenant başına",
    perf: "cache isabet oranı gecikmeyi düşürür; uygun TTL kritik",
    test: "cache geçersizleme ve rate limit eşiği sınanır",
    integ: "scale (cache/ratelimit) ve dx-api-gateway ile bağlı",
    ai: "AI cache/limit eşiği önerir; politika kararını ekip verir",
    owasp: "A04 güvenli-tasarım: rate limit kötüye kullanımı sınırlar",
    mu: "Ünite 14 hız ve adalet (cache/limit) temelini kurar",
  }),
  "edu-u15": D("Ünite 15", "UX Prensipleri — 60+ kullanıcı için tasarım: 60+ için iyi UX gençler için de daha iyidir", {
    kap: "yaş-kapsayıcı UX prensiplerini ve sadelik ilkesini öğretir",
    code: "tutarlı düzen, büyük dokunma hedefi, az adım",
    mob: "mobilde tek sütun, büyük hedef, az bilişsel yük",
    wcag: "WCAG 2.2 AAA: yüksek kontrast, net dil, hata toleransı (60+ için kritik)",
    test: "gerçek kullanıcı senaryosu ve erişilebilirlik denetimi",
    integ: "tüm UI yüzeyleri ve adr-0018 (AI-first UX) ile bağlı",
    ai: "AI UX iyileştirme önerir; tasarım kararını ekip verir",
    mu: "Ünite 15 kapsayıcı UX prensiplerini verir",
  }),
  "edu-u16": D("Ünite 16", "Test Piramidi — kodun hata yapmadığını kanıtlamak: çok unit, orta integration, az ve yavaş e2e", {
    kap: "test piramidini ve test-önce disiplinini öğretir",
    code: "tabanı geniş unit; tepe az e2e; ters piramit kaçınılır",
    test: "her seviye için uygun test türü ve kapsam eşiği",
    perf: "hızlı unit geri-bildirim; yavaş e2e seçici çalışır",
    integ: "test-önce felsefesi ve sus-conformance ile bağlı",
    ai: "AI test senaryosu önerir; kapsam/kabul kararını ekip verir",
    owasp: "güvenlik testleri de piramide dahil (negatif senaryolar)",
    mu: "Ünite 16 test stratejisi temelini kurar",
  }),
  "edu-u17": D("Ünite 17", "Git Disiplini — kod tarihi yönetimi: branch stratejisi, commit yazma, semantic versioning; vibecoding'de AI değişiklikleri", {
    kap: "branch stratejisi, commit disiplini ve semver'i öğretir",
    sec: "main korumalı; doğrudan push yerine PR+inceleme (AI dahil)",
    code: "anlamlı commit; semver kırıcı değişikliği işaretler",
    test: "PR kapıları (test/tip/lint) yeşil olmadan merge yok",
    integ: "dx-workflow ve adr-0024 (akış kapıları) ile bağlı",
    ai: "AI commit/PR taslağı önerir ve PR açabilir; merge kararını insan verir",
    mu: "Ünite 17 Git ve sürüm disiplinini verir",
  }),
  "edu-u18": D("Ünite 18", "Performans Ölçümü — yavaşı bulup düzeltmek: sezgi değil profiling + p95 latency, EXPLAIN ile DB, N+1 tespiti", {
    kap: "ölçüm-temelli performans (profiling, gecikme yüzdelikleri, EXPLAIN) öğretir",
    code: "N+1 sorgu tespiti; toplu/önbellekli erişim",
    perf: "p95/p99 gecikme ölçülür; EXPLAIN ile sorgu planı incelenir",
    test: "performans bütçesi ve regresyon ölçümle sınanır",
    integ: "edu-u04 (DB) ve scale kümesiyle bağlı",
    ai: "AI yavaş sorgu/darboğaz önerir; optimizasyon kararını geliştirici verir",
    mu: "Ünite 18 ölçüm-temelli performans disiplinini verir",
  }),
  "edu-u19": D("Ünite 19", "Güvenlik Tuzakları — OWASP Top 10: SQL injection, XSS, CSRF, IDOR ve fazlası", {
    kap: "en yaygın 10 web güvenlik açığını ve önlemini öğretir",
    sec: "her açık için somut önlem (parametreli sorgu, çıktı kaçışı, CSRF token, yetki kontrolü)",
    code: "girdi doğrulama + çıktı kaçışı + yetki kontrolü standart",
    test: "her açık türü için negatif (saldırı) senaryo testi",
    integ: "tüm güvenlik boyutlarının kavramsal kaynağı; crosscut (security) ile bağlı",
    ai: "AI olası açık deseni işaretler; düzeltme/kabul kararını güvenlik ekibi verir",
    owasp: "A01-A10 Top 10 tam kapsam bu ünitenin konusu",
    mu: "Ünite 19 web güvenlik tuzaklarının referansıdır",
  }),
  "edu-u20": D("Ünite 20", "Backup Disiplini — felaket önleme: backup yapmak yetmez, backup'tan dönmeyi test etmediysen backup yok demektir", {
    kap: "yedekleme ve geri-yükleme (restore) testi disiplinini öğretir",
    sec: "yedek şifreli; erişim dar; restore tatbikatı düzenli",
    code: "otomatik yedek + sürüm + saklama politikası",
    test: "restore tatbikatı düzenli yapılır (backup'tan dönüş kanıtı)",
    dep: "yedek farklı konum/bölgede; felaket kurtarma planı",
    integ: "edu-u10 (operations) ve risk defteriyle bağlı",
    ai: "AI yedek/restore boşluğu önerir; kurtarma planı kararını insan verir",
    mu: "Ünite 20 yedekleme ve felaket önleme disiplinini verir",
  }),
  "edu-u21": D("Ünite 21", "Money + Tax — para ve vergi derinleştirme: çoklu kur, kur tarihi, TR KDV %1/%8/%18, B2B reverse charge", {
    kap: "çoklu kur, kur tarihi ve TR vergi (KDV/reverse charge) kurallarını öğretir",
    sec: "para hesabı denetlenebilir; vergi kuralı yürürlük-tarihli ve izli",
    code: "para tam-sayı kuruş; kur tarihi sabitlenir; vergi tablodan",
    test: "KDV oranları, reverse charge ve kur dönüşümü doğruluk testi",
    integ: "finance (tax/billing) ve edu-u02b ile bağlı",
    ai: "AI vergi/kur kuralı önerir; mali kararı muhasebe/insan verir",
    owasp: "A04 güvenli-tasarım: para/vergi hatası yapısal önlenir",
    mu: "Ünite 21 para ve vergi derinliğini verir",
  }),
  "edu-u22": D("Ünite 22", "Email + SMS — bildirim güvenirliği: email gönderdin diye gelmez; SPF/DKIM/DMARC yoksa spam'a düşer", {
    kap: "e-posta teslim edilebilirliği (SPF/DKIM/DMARC) ve SMS güvenirliğini öğretir",
    sec: "kimlik doğrulama kayıtları sahteciliği önler; içerik PII'ye dikkat",
    code: "sağlayıcı adaptörü + yeniden-deneme; teslim durumu izlenir",
    perf: "toplu gönderim kuyruklu; hız sınırı sağlayıcıya uyumlu",
    test: "SPF/DKIM/DMARC ve teslim/başarısızlık senaryosu sınanır",
    integ: "services (e-posta/SMS adaptörü) ve comms ile bağlı",
    ai: "AI teslim sorunu/şablon önerir; gönderim politikası kararını ekip verir",
    mu: "Ünite 22 bildirim güvenirliği temelini kurar",
  }),
  "edu-u23": D("Ünite 23", "Dosya İşleme — yükleme, optimize, virüs taraması: 100MB dosya sunucuyu çökertir; presigned + antivirus", {
    kap: "güvenli dosya yükleme, boyut sınırı, virüs taraması ve presigned URL öğretir",
    sec: "yüklenen dosya taranır; tür/boyut doğrulanır; presigned ile doğrudan depo",
    code: "akış-temelli yükleme (bellek taşmaz); optimize/yeniden-boyutlandırma",
    perf: "presigned URL ile sunucu yükü azalır; büyük dosya akışla",
    test: "kötü-amaçlı dosya reddi ve boyut sınırı sınanır",
    integ: "services (depolama) ve file (layer1) ile bağlı",
    ai: "AI dosya işleme riski önerir; politika kararını ekip verir",
    owasp: "A04/A03: dosya doğrulama ve tarama bu ünitede",
    mu: "Ünite 23 güvenli dosya işleme temelini kurar",
  }),
  "edu-u24": D("Ünite 24", "Uluslararasılaştırma — 6 Eksen ve Görünmez Kurallar: locale değil 6 ayrı eksen; TR'de KVKK, AB'de GDPR", {
    kap: "i18n'in 6 eksenini (dil/biçim/zaman/para/hukuk/kültür) öğretir",
    sec: "bölgesel uyum (KVKK/GDPR) veri işlemeyi belirler",
    code: "metin dış kaynakta; biçim/zaman/para locale'e göre türetilir",
    test: "farklı locale'de biçim/zaman/para ve uyum kuralları sınanır",
    integ: "crosscut (i18n/jurisdiction) ve edu-u02b ile bağlı",
    ai: "AI çeviri/biçim önerir; hukuki uyum kararını sorumlu insan verir",
    owasp: "A09 uyum: bölgesel veri kuralları izlenir",
    mu: "Ünite 24 uluslararasılaştırma derinliğini verir",
  }),
  "edu-u25": D("Ünite 25", "ArcheType vs Klasik DDD — Anemic Domain Tuzağı: klasik DDD'de ayrı aggregate; meta-framework'te ArcheType runtime tanımlı", {
    kap: "ArcheType yaklaşımını klasik DDD ile karşılaştırır; anemic domain tuzağını açıklar",
    code: "davranış ArcheType sözleşmesinde; anemic (davranışsız) model kaçınılır",
    test: "domain kuralının modelde mi yoksa dışarıda mı olduğu sınanır",
    integ: "edu-u03 ve archetype sözleşme katmanıyla bağlı",
    ai: "AI model/aggregate önerir; domain tasarım kararını ekip verir",
    mu: "Ünite 25 ArcheType-DDD ilişkisini netleştirir",
  }),
  "edu-vibecoding-ilk-nokta": D("Vibecoding İlk Nokta", "Vibecoding'e Başlarken İlk Nokta — Hazır Komutlar: Claude/Cursor/Antigravity açıldığında ilk yazılacak bağlam komutları", {
    kap: "AI aracını doğru bağlamla başlatan ilk komutları verir",
    sec: "bağlam komutları sır içermez; AI sınırı baştan kurulur",
    code: "bağlam paketi (proje/stack/kural) ilk mesajda verilir",
    test: "ilk bağlam doğru kurulduğunda AI doğru stack'e uyar",
    integ: "adr-0012 (AGENTS/CLAUDE) ve prompt kütüphanesiyle bağlı",
    ai: "AI bu bağlamla çalışır; üreten-onaylayamaz ilkesi baştan kurulur",
    mu: "Vibecoding ilk nokta AI oturumunun doğru başlatılmasını sağlar",
  }),
  "edu-vibecoding-waterfall-fastapi": D("Vibecoding FastAPI", "Vibecoding ile FastAPI CMS İnşası — Waterfall Adımları: büyük resmi kaybetmeden topluluk eklentili bir CMS'i sıfırdan kurmak", {
    kap: "FastAPI tabanlı CMS'i waterfall fazlarıyla AI eşliğinde kurmayı öğretir",
    sec: "her fazda güvenlik kapısı; eklenti sandbox ilkesi",
    code: "faz faz ilerleme; her faz çıkışında çalışan kanıt",
    test: "her faz test-önce; çıkış kapısı yeşil olmadan ilerlenmez",
    dep: "CMS sonunda CI→dağıtım hattıyla yayınlanır",
    integ: "edu-waterfall-yol-haritasi ve build-sequence ile hizalı",
    ai: "AI faz adımı/scaffold önerir; faz kapanış kararını ekip verir",
    mu: "Vibecoding FastAPI ünitesi uçtan uca pratik inşa örneğidir",
  }),
};

apply("seed-edu", CONTENT);
